import { describe,it,expect,vi,afterEach } from 'vitest';
import { readScopeInvoiceCapture, type ScopeInvoiceCaptureReadClient } from './projectScopeInvoiceCapture';
import { scopeInvoiceInventoryFingerprint } from '../../../supabase/functions/_shared/project-scope-invoice-kernel-evidence.ts';
const actor='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',org='11111111-1111-4111-8111-111111111111',root='cccccccc-cccc-4ccc-8ccc-cccccccccccc';
const authority=()=>({actorId:actor,organizationId:org,accessToken:'synthetic-test-token',request:{schema_version:'operations-scope-invoice-capture-admin-read.v1' as const,root_kind:'large_project' as const,root_id:root,expected_composition_snapshot_id:actor}});
async function reply(){return {schema_version:'operations-scope-invoice-capture-admin-evidence.v1',authority_scope:'canonical_scope_invoice_capture',evidence:{schema_version:'operations-scope-invoice-kernel-evidence.v1',organization_id:org,economic_scope_id:'90909090-9090-4909-8909-909090909090',scope_snapshot_id:root,scope_revision:1,membership_fingerprint:'a'.repeat(64),composition_snapshot_id:actor,composition_revision:1,composition_fingerprint:'b'.repeat(64),root_kind:'large_project',root_id:root,currency:'SEK',membership_currentness:'as_of_graph',source_currentness:'saved_receiver_heads_only',captured_inventory_matches_current:true,captured_inventory_fingerprint:await scopeInvoiceInventoryFingerprint([]),as_of:'2026-10-02T00:00:00Z',members:[],source_inventory:[],saved_source_references:[],diagnostics:[],category_coverage:{personnel:'unavailable',supplier:'unavailable',catering:'unavailable',other:'unavailable'},source_coverage:'unavailable',credit_eligible:false,remaining_minor:null,eac_minor:null,budget_minor:null,shadow_only:true}};}
function client(data:unknown){const state={session:{access_token:'synthetic-test-token',user:{id:actor}},error:null as unknown,signal:null as AbortSignal|null};const getSession=vi.fn(async()=>({data:{session:state.session},error:null}));const header=vi.fn();const rpc=vi.fn((name,args)=>({setHeader:(key:string,value:string)=>{header(key,value);return {abortSignal:(signal:AbortSignal)=>{state.signal=signal;return Promise.resolve({data,error:state.error});}};}}));return {state,getSession,header,rpc,client:{auth:{getSession},rpc} as ScopeInvoiceCaptureReadClient};}
afterEach(()=>vi.useRealTimers());
describe('authenticated scope capture lifecycle',()=>{
 it('uses actual RPC purpose, captured token and unchanged copied evidence',async()=>{const value=await reply(),c=client(value),a=authority();expect(await readScopeInvoiceCapture(c.client,a,new AbortController().signal)).toBe(value);expect(c.rpc).toHaveBeenCalledWith('read_operations_scope_invoice_capture_admin_v1',{p_request:a.request});expect(c.header).toHaveBeenCalledWith('Authorization','Bearer synthetic-test-token');expect(c.getSession).toHaveBeenCalledTimes(2);});
 it('does not issue an RPC for invalid authority or an already aborted request',async()=>{const c=client(await reply()),abort=new AbortController();abort.abort();await expect(readScopeInvoiceCapture(c.client,authority(),abort.signal)).rejects.toThrow();await expect(readScopeInvoiceCapture(c.client,{...authority(),organizationId:'foreign'},new AbortController().signal)).rejects.toThrow();expect(c.rpc).not.toHaveBeenCalled();});
 it('rejects changed token or actor before sending and after async source validation',async()=>{for(const stage of [0,1]){const c=client(await reply());c.getSession.mockImplementation(async()=>({data:{session:{access_token:stage===0||c.getSession.mock.calls.length>1?'changed-token':'synthetic-test-token',user:{id:actor}}},error:null}));await expect(readScopeInvoiceCapture(c.client,authority(),new AbortController().signal)).rejects.toThrow('Sessionen');expect(c.rpc).toHaveBeenCalledTimes(stage);}});
 it('keeps authority/selection fixed when caller mutates its input during the request',async()=>{const a=authority(),c=client(await reply());c.getSession.mockImplementation(async()=>{a.accessToken='changed-token';a.organizationId=root;a.request.root_id=actor;return {data:{session:{access_token:'synthetic-test-token',user:{id:actor}}},error:null};});const result=await readScopeInvoiceCapture(c.client,a,new AbortController().signal);expect(result.evidence.root_id).toBe(root);expect(c.header).toHaveBeenCalledWith('Authorization','Bearer synthetic-test-token');});
 it('distinguishes business-stale from other backend errors without exposing raw messages',async()=>{const c=client(await reply());c.state.error={code:'PT409',message:'secret-test-detail'};await expect(readScopeInvoiceCapture(c.client,authority(),new AbortController().signal)).rejects.toThrow('har ändrats');c.state.error={code:'42501',message:'secret-test-detail'};await expect(readScopeInvoiceCapture(c.client,authority(),new AbortController().signal)).rejects.toThrow('kunde inte hämtas');});
 it('bounds a hung session call even when it ignores cancellation',async()=>{vi.useFakeTimers();const c=client(await reply());c.getSession.mockImplementation(()=>new Promise(()=>{}));const pending=readScopeInvoiceCapture(c.client,authority(),new AbortController().signal);const assertion=expect(pending).rejects.toThrow('avbröts');await vi.advanceTimersByTimeAsync(15000);await assertion;expect(c.rpc).not.toHaveBeenCalled();});
 it('aborts and discards a late RPC result when caller cancellation is ignored',async()=>{const c=client(await reply()),abort=new AbortController();let resolve:(v:{data:unknown;error:unknown})=>void=()=>{};c.rpc.mockImplementation(()=>({setHeader:()=>({abortSignal:(signal:AbortSignal)=>{c.state.signal=signal;return new Promise(r=>{resolve=r;});}})}));const pending=readScopeInvoiceCapture(c.client,authority(),abort.signal),assertion=expect(pending).rejects.toThrow('avbröts');await Promise.resolve();await Promise.resolve();abort.abort();await assertion;resolve({data:await reply(),error:null});expect(c.state.signal?.aborted).toBe(true);});
});
