import { supabase } from "@/integrations/supabase/client";
import {
  WarehouseProject,
  WarehouseProjectInboxItem,
  WarehouseProjectTask,
} from "@/types/warehouseProject";
import { PackingWithBooking } from "@/types/packing";
import { syncBookingToPacking } from "@/services/booking/bookingPackingSyncService";

// ============================================================================
// Inbox
// ============================================================================
export const fetchInbox = async (
  status: 'new' | 'all' = 'new'
): Promise<WarehouseProjectInboxItem[]> => {
  let q = supabase
    .from('warehouse_project_inbox')
    .select('*')
    .order('created_at', { ascending: false });
  if (status === 'new') q = q.eq('status', 'new');
  const { data, error } = await q;
  if (error) throw error;
  return (data || []) as WarehouseProjectInboxItem[];
};

export const dismissInboxItem = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_project_inbox')
    .update({ status: 'dismissed', processed_at: new Date().toISOString() })
    .eq('id', id);
  if (error) throw error;
};

// ============================================================================
// Warehouse Projects
// ============================================================================
export const fetchWarehouseProjects = async (): Promise<WarehouseProject[]> => {
  const { data, error } = await supabase
    .from('warehouse_projects')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data || []) as WarehouseProject[];
};

export const fetchWarehouseProject = async (id: string): Promise<WarehouseProject | null> => {
  const { data, error } = await supabase
    .from('warehouse_projects')
    .select('*')
    .eq('id', id)
    .single();
  if (error) throw error;
  return (data || null) as WarehouseProject | null;
};

export interface SuggestedTaskDates {
  packStart: string | null;
  packEnd: string | null;
  returnStart: string | null;
  returnEnd: string | null;
}

const addDays = (iso: string, days: number): string => {
  const d = new Date(iso);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export const fetchInboxItemSuggestedDates = async (
  item: WarehouseProjectInboxItem
): Promise<SuggestedTaskDates> => {
  let eventDate: string | null = null;
  let rigdownDate: string | null = null;

  if (item.source_type === 'project') {
    // projects.booking_id -> bookings.eventdate / rigdowndate
    const { data: proj } = await supabase
      .from('projects')
      .select('booking_id')
      .eq('id', item.source_id)
      .maybeSingle();
    if (proj?.booking_id) {
      const { data: booking } = await supabase
        .from('bookings')
        .select('eventdate, rigdowndate')
        .eq('id', proj.booking_id)
        .maybeSingle();
      eventDate = booking?.eventdate ?? null;
      rigdownDate = booking?.rigdowndate ?? eventDate;
    }
  } else if (item.source_type === 'large_project') {
    const { data: lp } = await supabase
      .from('large_projects')
      .select('event_date, end_date')
      .eq('id', item.source_id)
      .maybeSingle();
    const events = (lp?.event_date || []).filter(Boolean).sort();
    const ends = (lp?.end_date || []).filter(Boolean).sort();
    eventDate = events[0] || item.event_date || null;
    rigdownDate = ends[ends.length - 1] || eventDate;
  }

  if (!eventDate) eventDate = item.event_date;
  if (!rigdownDate) rigdownDate = eventDate;

  return {
    packStart: eventDate ? addDays(eventDate, -3) : null,
    packEnd: eventDate ? addDays(eventDate, -1) : null,
    returnStart: rigdownDate ? addDays(rigdownDate, 1) : null,
    returnEnd: rigdownDate ? addDays(rigdownDate, 2) : null,
  };
};

export interface CreateFromInboxOptions {
  name: string;
  packStart: string;
  packEnd: string;
  returnStart: string;
  returnEnd: string;
}

export const createWarehouseProjectFromInbox = async (
  inboxItem: WarehouseProjectInboxItem,
  options: CreateFromInboxOptions
): Promise<WarehouseProject> => {
  const { data: { user } } = await supabase.auth.getUser();

  // Insert warehouse project — project_number is auto-generated by trigger
  const { data: wp, error: wpError } = await supabase
    .from('warehouse_projects')
    .insert({
      name: options.name || inboxItem.client_name || 'Lagerprojekt',
      source_project_id: inboxItem.source_type === 'project' ? inboxItem.source_id : null,
      source_large_project_id: inboxItem.source_type === 'large_project' ? inboxItem.source_id : null,
      source_project_number: inboxItem.source_project_number,
      status: 'planning',
      created_by: user?.id ?? null,
      project_number: '', // trigger fills this
    } as any)
    .select()
    .single();

  if (wpError) throw wpError;

  // Insert the two mandatory tasks (Packa + Returnera)
  const { error: tasksError } = await supabase
    .from('warehouse_project_tasks')
    .insert([
      {
        warehouse_project_id: wp.id,
        title: 'Packa',
        start_date: options.packStart,
        end_date: options.packEnd,
        status: 'planning',
        sort_order: 0,
      },
      {
        warehouse_project_id: wp.id,
        title: 'Returnera',
        start_date: options.returnStart,
        end_date: options.returnEnd,
        status: 'planning',
        sort_order: 1,
      },
    ] as any);

  if (tasksError) {
    console.error('Failed to create default tasks:', tasksError);
    // Don't throw — project is created, tasks can be added later
  }

  // Mark inbox as converted
  await supabase
    .from('warehouse_project_inbox')
    .update({
      status: 'converted',
      processed_at: new Date().toISOString(),
      warehouse_project_id: wp.id,
    })
    .eq('id', inboxItem.id);

  return wp as WarehouseProject;
};

export const updateWarehouseProject = async (
  id: string,
  updates: Partial<WarehouseProject>
): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_projects')
    .update(updates)
    .eq('id', id);
  if (error) throw error;
};

export const deleteWarehouseProject = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_projects')
    .delete()
    .eq('id', id);
  if (error) throw error;
};

// ============================================================================
// Tasks (free moments inside a warehouse project)
// ============================================================================
export const fetchWarehouseProjectTasks = async (
  warehouseProjectId: string
): Promise<WarehouseProjectTask[]> => {
  const { data, error } = await supabase
    .from('warehouse_project_tasks')
    .select('*')
    .eq('warehouse_project_id', warehouseProjectId)
    .order('sort_order', { ascending: true });
  if (error) throw error;
  return (data || []) as WarehouseProjectTask[];
};

export const createWarehouseProjectTask = async (task: {
  warehouse_project_id: string;
  title: string;
  description?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  assigned_to?: string | null;
}): Promise<WarehouseProjectTask> => {
  const { data, error } = await supabase
    .from('warehouse_project_tasks')
    .insert(task as any)
    .select()
    .single();
  if (error) throw error;
  return data as WarehouseProjectTask;
};

export const updateWarehouseProjectTask = async (
  id: string,
  updates: Partial<WarehouseProjectTask>
): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_project_tasks')
    .update(updates)
    .eq('id', id);
  if (error) throw error;
};

export const deleteWarehouseProjectTask = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_project_tasks')
    .delete()
    .eq('id', id);
  if (error) throw error;
};
