import { supabase } from "@/integrations/supabase/client";
import {
  WarehouseProject,
  WarehouseProjectInboxItem,
  WarehouseProjectTask,
} from "@/types/warehouseProject";
import { PackingWithBooking } from "@/types/packing";
import { syncBookingToPacking } from "@/services/booking/bookingPackingSyncService";

// ============================================================================
// Inbox
// ============================================================================
export const fetchInbox = async (
  status: 'new' | 'all' = 'new'
): Promise<WarehouseProjectInboxItem[]> => {
  let q = supabase
    .from('warehouse_project_inbox')
    .select('*')
    .order('created_at', { ascending: false });
  if (status === 'new') q = q.eq('status', 'new');
  const { data, error } = await q;
  if (error) throw error;
  return (data || []) as WarehouseProjectInboxItem[];
};

export const dismissInboxItem = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_project_inbox')
    .update({ status: 'dismissed', processed_at: new Date().toISOString() })
    .eq('id', id);
  if (error) throw error;
};

// ============================================================================
// Warehouse Projects
// ============================================================================
export const fetchWarehouseProjects = async (): Promise<WarehouseProject[]> => {
  const { data, error } = await supabase
    .from('warehouse_projects')
    .select('*')
    .order('created_at', { ascending: false });
  if (error) throw error;
  return (data || []) as WarehouseProject[];
};

export const fetchWarehouseProject = async (id: string): Promise<WarehouseProject | null> => {
  const { data, error } = await supabase
    .from('warehouse_projects')
    .select('*')
    .eq('id', id)
    .single();
  if (error) throw error;
  return (data || null) as WarehouseProject | null;
};

export interface SuggestedTaskDates {
  packStart: string | null;
  packEnd: string | null;
  returnStart: string | null;
  returnEnd: string | null;
}

const addDays = (iso: string, days: number): string => {
  const d = new Date(iso);
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
};

export const fetchInboxItemSuggestedDates = async (
  item: WarehouseProjectInboxItem
): Promise<SuggestedTaskDates> => {
  let eventDate: string | null = null;
  let rigdownDate: string | null = null;

  if (item.source_type === 'project') {
    // projects.booking_id -> bookings.eventdate / rigdowndate
    const { data: proj } = await supabase
      .from('projects')
      .select('booking_id')
      .eq('id', item.source_id)
      .maybeSingle();
    if (proj?.booking_id) {
      const { data: booking } = await supabase
        .from('bookings')
        .select('eventdate, rigdowndate')
        .eq('id', proj.booking_id)
        .maybeSingle();
      eventDate = booking?.eventdate ?? null;
      rigdownDate = booking?.rigdowndate ?? eventDate;
    }
  } else if (item.source_type === 'large_project') {
    const { data: lp } = await supabase
      .from('large_projects')
      .select('event_date, end_date')
      .eq('id', item.source_id)
      .maybeSingle();
    const events = (lp?.event_date || []).filter(Boolean).sort();
    const ends = (lp?.end_date || []).filter(Boolean).sort();
    eventDate = events[0] || item.event_date || null;
    rigdownDate = ends[ends.length - 1] || eventDate;
  }

  if (!eventDate) eventDate = item.event_date;
  if (!rigdownDate) rigdownDate = eventDate;

  return {
    packStart: eventDate ? addDays(eventDate, -3) : null,
    packEnd: eventDate ? addDays(eventDate, -1) : null,
    returnStart: rigdownDate ? addDays(rigdownDate, 1) : null,
    returnEnd: rigdownDate ? addDays(rigdownDate, 2) : null,
  };
};

export interface CreateFromInboxOptions {
  name: string;
  packStart: string;
  packEnd: string;
  /** Optional — vissa projekt har ingen retur (t.ex. förbrukningsmaterial). */
  returnStart: string | null;
  returnEnd: string | null;
}

export const createWarehouseProjectFromInbox = async (
  inboxItem: WarehouseProjectInboxItem,
  options: CreateFromInboxOptions
): Promise<WarehouseProject> => {
  const { data: { user } } = await supabase.auth.getUser();

  // Insert warehouse project — project_number is auto-generated by trigger
  const { data: wp, error: wpError } = await supabase
    .from('warehouse_projects')
    .insert({
      name: options.name || inboxItem.client_name || 'Lagerprojekt',
      source_project_id: inboxItem.source_type === 'project' ? inboxItem.source_id : null,
      source_large_project_id: inboxItem.source_type === 'large_project' ? inboxItem.source_id : null,
      source_project_number: inboxItem.source_project_number,
      status: 'planning',
      created_by: user?.id ?? null,
      project_number: '', // trigger fills this
    } as any)
    .select()
    .single();

  if (wpError) throw wpError;

  // Insert the two mandatory tasks (Packa + Returnera)
  const { error: tasksError } = await supabase
    .from('warehouse_project_tasks')
    .insert([
      {
        warehouse_project_id: wp.id,
        title: 'Packning',
        start_date: options.packStart,
        end_date: options.packEnd,
        status: 'planning',
        sort_order: 0,
      },
      {
        warehouse_project_id: wp.id,
        title: 'Retur',
        start_date: options.returnStart,
        end_date: options.returnEnd,
        status: 'planning',
        sort_order: 1,
      },
    ] as any);

  if (tasksError) {
    console.error('Failed to create default tasks:', tasksError);
    // Don't throw — project is created, tasks can be added later
  }

  // Auto-create packing_projects for the source booking(s) — non-blocking
  try {
    await createPackingsForWarehouseProject(wp as WarehouseProject, inboxItem);
  } catch (err) {
    console.error('Failed to auto-create packings for warehouse project:', err);
  }

  // Mark inbox as converted
  await supabase
    .from('warehouse_project_inbox')
    .update({
      status: 'converted',
      processed_at: new Date().toISOString(),
      warehouse_project_id: wp.id,
    })
    .eq('id', inboxItem.id);

  return wp as WarehouseProject;
};

// ============================================================================
// Auto-create packings for newly created warehouse project
// ============================================================================
const createPackingsForWarehouseProject = async (
  wp: WarehouseProject,
  inboxItem: WarehouseProjectInboxItem
): Promise<void> => {
  if (inboxItem.source_type === 'project') {
    const { data: proj } = await supabase
      .from('projects')
      .select('booking_id')
      .eq('id', inboxItem.source_id)
      .maybeSingle();

    const bookingId = proj?.booking_id;
    if (!bookingId) return;

    const { data: booking } = await supabase
      .from('bookings')
      .select('id, client, eventdate, rigdaydate, rigdowndate, deliveryaddress, internalnotes, organization_id')
      .eq('id', bookingId)
      .maybeSingle();
    if (!booking) return;

    // Re-use existing packing if one already exists for this booking
    const { data: existing } = await supabase
      .from('packing_projects')
      .select('id')
      .eq('booking_id', bookingId)
      .is('large_project_id', null)
      .maybeSingle();

    if (existing) {
      await supabase
        .from('packing_projects')
        .update({ warehouse_project_id: wp.id })
        .eq('id', existing.id);
      syncBookingToPacking(bookingId, booking.organization_id);
      return;
    }

    const dateStr = booking.eventdate
      ? new Date(booking.eventdate).toISOString().slice(0, 10)
      : '';
    const packingName = `${booking.client}${dateStr ? ` - ${dateStr}` : ''}`;

    const { error: insertError } = await supabase
      .from('packing_projects')
      .insert({
        name: packingName,
        booking_id: bookingId,
        warehouse_project_id: wp.id,
        client_name: booking.client,
        start_date: booking.rigdaydate,
        end_date: booking.rigdowndate,
        delivery_address: booking.deliveryaddress,
        notes: booking.internalnotes,
        status: 'planning',
        organization_id: booking.organization_id,
      } as any);

    if (insertError) {
      console.error('Failed to create packing for booking:', insertError);
      return;
    }

    syncBookingToPacking(bookingId, booking.organization_id);
    return;
  }

  if (inboxItem.source_type === 'large_project') {
    const { data: lpBookings } = await supabase
      .from('large_project_bookings')
      .select('booking_id')
      .eq('large_project_id', inboxItem.source_id);

    const bookingIds = (lpBookings || []).map(b => b.booking_id).filter(Boolean) as string[];
    if (bookingIds.length === 0) return;

    const { data: bookings } = await supabase
      .from('bookings')
      .select('id, client, eventdate, rigdaydate, rigdowndate, deliveryaddress, internalnotes, organization_id')
      .in('id', bookingIds);
    if (!bookings || bookings.length === 0) return;

    // Avoid duplicate consolidated packing
    const { data: existingConsolidated } = await supabase
      .from('packing_projects')
      .select('id')
      .eq('large_project_id', inboxItem.source_id)
      .maybeSingle();

    if (existingConsolidated) {
      await supabase
        .from('packing_projects')
        .update({ warehouse_project_id: wp.id })
        .eq('id', existingConsolidated.id);
      for (const b of bookings) {
        syncBookingToPacking(b.id, b.organization_id);
      }
      return;
    }

    const orgId = bookings[0].organization_id;
    const rigDates = bookings.map(b => b.rigdaydate).filter(Boolean) as string[];
    const rigdownDates = bookings.map(b => b.rigdowndate).filter(Boolean) as string[];
    const startDate = rigDates.length > 0 ? rigDates.sort()[0] : null;
    const endDate = rigdownDates.length > 0 ? rigdownDates.sort().reverse()[0] : null;

    const { data: lp } = await supabase
      .from('large_projects')
      .select('name')
      .eq('id', inboxItem.source_id)
      .maybeSingle();
    const packingName = lp?.name || inboxItem.client_name || 'Lagerprojekt';

    const { data: newPacking, error: insertError } = await supabase
      .from('packing_projects')
      .insert({
        name: packingName,
        booking_id: bookings[0].id,
        large_project_id: inboxItem.source_id,
        warehouse_project_id: wp.id,
        client_name: bookings[0].client,
        delivery_address: bookings[0].deliveryaddress,
        notes: bookings[0].internalnotes,
        start_date: startDate,
        end_date: endDate,
        status: 'planning',
        organization_id: orgId,
      } as any)
      .select('id')
      .single();

    if (insertError || !newPacking) {
      console.error('Failed to create consolidated packing:', insertError);
      return;
    }

    const links = bookings.map(b => ({
      packing_id: newPacking.id,
      booking_id: b.id,
      organization_id: b.organization_id,
    }));
    await supabase.from('packing_project_bookings').insert(links);

    for (const b of bookings) {
      syncBookingToPacking(b.id, b.organization_id);
    }
  }
};

// ============================================================================
// Packings linked to a warehouse project
// ============================================================================
export const fetchWarehousePackings = async (
  warehouseProjectId: string
): Promise<PackingWithBooking[]> => {
  const { data: packings, error } = await supabase
    .from('packing_projects')
    .select('*')
    .eq('warehouse_project_id', warehouseProjectId)
    .order('created_at', { ascending: false });
  if (error) throw error;

  const list = (packings || []) as any[];
  if (list.length === 0) return [];

  const bookingIds = list.map(p => p.booking_id).filter(Boolean) as string[];
  const bookingMap = new Map<string, any>();
  if (bookingIds.length > 0) {
    const { data: bookings } = await supabase
      .from('bookings')
      .select('id, client, eventdate, rigdaydate, rigdowndate, deliveryaddress, contact_name, contact_phone, contact_email, booking_number')
      .in('id', bookingIds);
    (bookings || []).forEach(b => bookingMap.set(b.id, b));
  }

  return list.map(p => ({
    ...p,
    booking: p.booking_id ? bookingMap.get(p.booking_id) || null : null,
  })) as PackingWithBooking[];
};

export const updateWarehouseProject = async (
  id: string,
  updates: Partial<WarehouseProject>
): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_projects')
    .update(updates)
    .eq('id', id);
  if (error) throw error;
};

export const deleteWarehouseProject = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_projects')
    .delete()
    .eq('id', id);
  if (error) throw error;
};

// ============================================================================
// Tasks (free moments inside a warehouse project)
// ============================================================================
export const fetchWarehouseProjectTasks = async (
  warehouseProjectId: string
): Promise<WarehouseProjectTask[]> => {
  const { data, error } = await supabase
    .from('warehouse_project_tasks')
    .select('*')
    .eq('warehouse_project_id', warehouseProjectId)
    .order('sort_order', { ascending: true });
  if (error) throw error;
  return (data || []) as WarehouseProjectTask[];
};

export const createWarehouseProjectTask = async (task: {
  warehouse_project_id: string;
  title: string;
  description?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  assigned_to?: string | null;
  category?: string | null;
}): Promise<WarehouseProjectTask> => {
  const { data, error } = await supabase
    .from('warehouse_project_tasks')
    .insert(task as any)
    .select()
    .single();
  if (error) throw error;
  return data as WarehouseProjectTask;
};

export const updateWarehouseProjectTask = async (
  id: string,
  updates: Partial<WarehouseProjectTask>
): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_project_tasks')
    .update(updates)
    .eq('id', id);
  if (error) throw error;
};

export const deleteWarehouseProjectTask = async (id: string): Promise<void> => {
  const { error } = await supabase
    .from('warehouse_project_tasks')
    .delete()
    .eq('id', id);
  if (error) throw error;
};

// ============================================================================
// Internal "Lager" project helpers
// Konsoliderat: använder samma `projects.is_internal = true` Lager som tidappen.
// Tidigare lagrades dessa i warehouse_projects, men det skapade ett dubbelt
// "Lager" — nu är de samma entitet, så tidregistrering på Lager hamnar rätt.
// ============================================================================
export interface InternalLagerProject {
  id: string;
  organization_id: string;
  name: string;
  is_internal: boolean;
}

export const fetchInternalWarehouseProject = async (): Promise<InternalLagerProject | null> => {
  const { data, error } = await supabase
    .from('projects')
    .select('id, organization_id, name, is_internal')
    .eq('is_internal', true)
    .maybeSingle();
  if (error) throw error;
  return (data || null) as InternalLagerProject | null;
};

export interface CreateInternalTaskInput {
  title: string;
  description?: string | null;
  /** Backwards-compat single assignee */
  assigned_to?: string | null;
  /** Preferred: assign one or more staff members */
  assigned_to_ids?: string[] | null;
  start_date?: string | null;
  end_date?: string | null;
  category?: string | null;
}

/**
 * Pick a lager-N team for the assignee on a given date:
 * 1. If assignee is in staff_assignments for that date with a lager-team → use it.
 * 2. Otherwise, find first lager-N (1..10) without conflicting internal_task in
 *    [start, end). Auto-expands to lager-4, lager-5… as needed.
 */
const pickLagerTeamForInternalTask = async (
  organizationId: string,
  startISO: string,
  endISO: string,
  assignedStaffId: string | null
): Promise<string> => {
  const dateKey = startISO.slice(0, 10);

  // 1. If staff is already on a lager-team that day, use that team.
  if (assignedStaffId) {
    const { data: existing } = await supabase
      .from('staff_assignments')
      .select('team_id')
      .eq('staff_id', assignedStaffId)
      .eq('assignment_date', dateKey);
    const lagerTeam = (existing || [])
      .map(r => r.team_id)
      .find(t => typeof t === 'string' && t.startsWith('lager-'));
    if (lagerTeam) return lagerTeam;
  }

  // 2. Find first lager-N without overlap on that day.
  const { data: dayEvents } = await supabase
    .from('warehouse_calendar_events')
    .select('resource_id, start_time, end_time')
    .gte('start_time', `${dateKey}T00:00:00`)
    .lt('start_time', `${dateKey}T23:59:59`);

  const startMs = new Date(startISO).getTime();
  const endMs = new Date(endISO).getTime();

  for (let n = 1; n <= 10; n++) {
    const id = `lager-${n}`;
    const overlaps = (dayEvents || []).some(ev => {
      if (ev.resource_id !== id) return false;
      const s = new Date(ev.start_time).getTime();
      const e = new Date(ev.end_time).getTime();
      return startMs < e && endMs > s;
    });
    if (!overlaps) return id;
  }
  return 'lager-1';
};

export const createInternalWarehouseTask = async (
  input: CreateInternalTaskInput
): Promise<{ id: string }> => {
  const project = await fetchInternalWarehouseProject();
  if (!project) {
    throw new Error('Lagerprojektet (Lager) saknas. Ladda om sidan eller kontakta admin.');
  }

  // Accept either pure date (yyyy-MM-dd) or full ISO datetime
  const toISO = (v: string | null | undefined, fallbackTime: string): string => {
    if (!v) return `${new Date().toISOString().slice(0, 10)}T${fallbackTime}`;
    return v.length === 10 ? `${v}T${fallbackTime}` : v;
  };
  const startISO = toISO(input.start_date, '08:00:00');
  const endISO = toISO(input.end_date || input.start_date, '11:00:00');

  // Normalize assignees: prefer assigned_to_ids, fall back to single assigned_to.
  const assigneeIds: string[] = (input.assigned_to_ids && input.assigned_to_ids.length > 0)
    ? input.assigned_to_ids
    : (input.assigned_to ? [input.assigned_to] : []);

  const { data: task, error } = await supabase
    .from('project_tasks')
    .insert({
      project_id: project.id,
      title: input.title,
      description: input.description ?? null,
      assigned_to: assigneeIds[0] ?? null,
      assigned_to_ids: assigneeIds.length > 0 ? assigneeIds : null,
      start_date: new Date(startISO).toISOString(),
      end_date: new Date(endISO).toISOString(),
      category: input.category ?? null,
    } as any)
    .select('id')
    .single();

  if (error) throw error;

  // Pick a lager-team per assignee so each person ends up in their own
  // planned lager-column. If no assignees, place a single event in the first
  // available lager team.
  const teamsToInsert: string[] = [];
  if (assigneeIds.length === 0) {
    teamsToInsert.push(
      await pickLagerTeamForInternalTask(project.organization_id, startISO, endISO, null)
    );
  } else {
    for (const sid of assigneeIds) {
      const team = await pickLagerTeamForInternalTask(
        project.organization_id, startISO, endISO, sid
      );
      if (!teamsToInsert.includes(team)) teamsToInsert.push(team);
    }
  }

  const events = teamsToInsert.map(resourceId => ({
    title: input.title,
    start_time: new Date(startISO).toISOString(),
    end_time: new Date(endISO).toISOString(),
    resource_id: resourceId,
    event_type: 'internal_task',
    manually_adjusted: true,
    organization_id: project.organization_id,
  }));

  const { error: calErr } = await supabase
    .from('warehouse_calendar_events')
    .insert(events as any);

  if (calErr) {
    console.error('Failed to create warehouse calendar event for internal task:', calErr);
    throw new Error(`Uppgiften skapades men kunde inte placeras i kalendern: ${calErr.message}`);
  }

  return task as { id: string };
};
