import {describe,it,expect} from 'vitest';
import {buildProjectScopeMembership,projectScopeMembershipFingerprint,type ScopeServerCatalog} from './canonical-project-scope.ts';
import {previewScopeViewAlias,validateScopeViewAliasCommand,assertScopeViewAliasPreviewMatches,type ScopeAliasCanonicalContext,type ScopeAliasMemberOwner,type ScopeViewAliasPreview} from './canonical-scope-view-alias.ts';
const org='11111111-1111-4111-8111-111111111111',foreign='99999999-9999-4999-8999-999999999999',scope='12121212-1212-4212-8212-121212121212';
const a='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',b='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',large='cccccccc-cccc-4ccc-8ccc-cccccccccccc',pack='dddddddd-dddd-4ddd-8ddd-dddddddddddd',j1='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',j2='ffffffff-ffff-4fff-8fff-ffffffffffff';
function catalog():ScopeServerCatalog{return {projects:[{id:a,organization_id:org,booking_id:'Order-ä-01',deleted_at:null},{id:b,organization_id:org,booking_id:'Order-𐀀-02',deleted_at:null}],large_projects:[{id:large,organization_id:org,primary_booking_id:'Order-ä-01',deleted_at:null}],packing_projects:[{id:pack,organization_id:org,booking_id:'Order-ä-01',large_project_id:large,status:'delivered'}],bookings:[{id:'Order-ä-01',organization_id:org,large_project_id:null},{id:'Order-𐀀-02',organization_id:org,large_project_id:null}],large_project_bookings:[{id:j1,organization_id:org,large_project_id:large,booking_id:'Order-ä-01'},{id:j2,organization_id:org,large_project_id:large,booking_id:'Order-𐀀-02'}],packing_project_bookings:[],allowed_packing_statuses:['delivered']};}
async function fixture(){const c=catalog(),membership=buildProjectScopeMembership(org,'large_project',large,c);const context:ScopeAliasCanonicalContext={organization_id:org,economic_scope_id:scope,canonical_root_kind:'large_project',canonical_root_id:large,canonical_scope_revision:2,canonical_membership_fingerprint:await projectScopeMembershipFingerprint(membership)};
const owners:ScopeAliasMemberOwner[]=[...membership.source_project_ids.map(member_id=>({organization_id:org,member_kind:'source_project' as const,member_id,economic_scope_id:scope,first_scope_revision:1})),...membership.local_booking_ids.map(member_id=>({organization_id:org,member_kind:'local_booking' as const,member_id,economic_scope_id:scope,first_scope_revision:1}))];return {c,context,owners};}
function command(p:ScopeViewAliasPreview){return {schema_version:'operations-canonical-scope-view-alias.v1',economic_scope_id:p.economic_scope_id,view_root_kind:p.view_membership.root_kind,view_root_id:p.view_membership.root_id,expected_alias_revision:0,expected_canonical_scope_revision:p.canonical_scope_revision,expected_canonical_membership_fingerprint:p.canonical_membership_fingerprint,expected_view_membership_fingerprint:p.view_membership_fingerprint,expected_catalog_fingerprint:p.catalog_fingerprint,idempotency_key:'synthetic-view-alias',reason:'Display explicitly declared full canonical scope'};}
describe('canonical view alias contract only',()=>{
  it('labels a leaf alias as full canonical scope and exposes the genuine extra booking/project without pricing or grant claims',async()=>{const f=await fixture(),p=await previewScopeViewAlias(f.context,'project',a,f.c,f.owners);expect(p.view_membership.local_booking_ids).toEqual(['Order-ä-01']);expect(p.canonical_membership.local_booking_ids).toEqual(['Order-ä-01','Order-𐀀-02']);expect(p.additional_local_booking_ids).toEqual(['Order-𐀀-02']);expect(p.additional_source_project_ids).toEqual([b]);expect(p.display_scope).toBe('full_canonical_scope');expect(p.required_authority).toBe('live_organization_admin');expect(p.integration_state).toBe('contract_only');expect(p.eac_minor).toBeNull();expect(Object.hasOwn(p,'amount_minor')).toBe(false);expect(assertScopeViewAliasPreviewMatches(command(p),p)).toEqual(command(p));});
  it('retains actual packing status and parent edges without inventing deleted_at or leaf authorization',async()=>{const f=await fixture(),p=await previewScopeViewAlias(f.context,'packing_project',pack,f.c,f.owners);expect(p.view_membership.root_evidence.packing_parent_id).toBe(large);expect(p.view_membership.relationships.some(r=>r.relation==='large_parent_booking'&&r.relation_id===j1)).toBe(true);f.c.allowed_packing_statuses=[];await expect(previewScopeViewAlias(f.context,'packing_project',pack,f.c,f.owners)).rejects.toThrow('scope_packing_missing_or_unenrolled');});
  it('rejects a whole master view alias into a partial project canonical scope',async()=>{const f=await fixture();f.context.canonical_root_kind='project';f.context.canonical_root_id=a;f.context.canonical_membership_fingerprint=await projectScopeMembershipFingerprint(buildProjectScopeMembership(org,'project',a,f.c));f.owners=f.owners.filter(o=>o.member_id===a||o.member_id==='Order-ä-01');await expect(previewScopeViewAlias(f.context,'large_project',large,f.c,f.owners)).rejects.toThrow('alias_view_outside_canonical_scope');});
  it('requires every permanent current member owner, same tenant/scope, unique rows and valid historical revision',async()=>{for(const change of ['missing','duplicate','foreign','other_scope','future'] as const){const f=await fixture();if(change==='missing')f.owners.pop();if(change==='duplicate')f.owners.push({...f.owners[0]});if(change==='foreign')f.owners[0].organization_id=foreign;if(change==='other_scope')f.owners[0].economic_scope_id=foreign;if(change==='future')f.owners[0].first_scope_revision=3;await expect(previewScopeViewAlias(f.context,'project',a,f.c,f.owners)).rejects.toThrow();}});
  it('preserves TEXT booking identities and produces identical hashes under row reordering and UUID casing',async()=>{const f=await fixture(),p=await previewScopeViewAlias(f.context,'project',a,f.c,f.owners);f.c.projects.reverse();f.c.bookings.reverse();f.c.large_project_bookings.reverse();f.c.large_projects[0].id=large.toUpperCase();f.owners.reverse();f.owners[0].organization_id=org.toUpperCase();f.context.canonical_root_id=large.toUpperCase();const q=await previewScopeViewAlias(f.context,'project',a.toUpperCase(),f.c,f.owners);expect(q).toEqual(p);expect(q.canonical_membership.local_booking_ids[0]).toBe('Order-ä-01');});
  it('captures input synchronously so caller mutation during hash await cannot create mixed graph evidence',async()=>{const f=await fixture(),pending=previewScopeViewAlias(f.context,'project',a,f.c,f.owners);f.c.projects[1].deleted_at='2026-10-02';f.owners[0].economic_scope_id=foreign;f.context.canonical_scope_revision=999;const p=await pending;expect(p.canonical_scope_revision).toBe(2);expect(p.canonical_membership.source_project_ids).toContain(b);});
  it('invalidates canonical graph changes and separately binds exact view parent edge identities',async()=>{const f=await fixture(),p=await previewScopeViewAlias(f.context,'packing_project',pack,f.c,f.owners);f.c.large_project_bookings[0].id='34343434-3434-4343-8343-343434343434';await expect(previewScopeViewAlias(f.context,'packing_project',pack,f.c,f.owners)).rejects.toThrow('alias_canonical_graph_stale');f.context.canonical_membership_fingerprint=await projectScopeMembershipFingerprint(buildProjectScopeMembership(org,'large_project',large,f.c));const q=await previewScopeViewAlias(f.context,'packing_project',pack,f.c,f.owners);expect(q.view_membership_fingerprint).not.toBe(p.view_membership_fingerprint);expect(q.catalog_fingerprint).not.toBe(p.catalog_fingerprint);});
  it('rejects strict command impersonation, monetary fields, coercions, invalid bounds and stale preview tokens',async()=>{const f=await fixture(),p=await previewScopeViewAlias(f.context,'project',a,f.c,f.owners),valid=command(p);for(const bad of [{...valid,organization_id:org},{...valid,actor_id:a},{...valid,amount_minor:0},{...valid,expected_alias_revision:'0'},{...valid,expected_alias_revision:Number.MAX_SAFE_INTEGER},{...valid,expected_canonical_scope_revision:0},{...valid,expected_catalog_fingerprint:[p.catalog_fingerprint]},{...valid,reason:' '}])expect(()=>validateScopeViewAliasCommand(bad)).toThrow('invalid_scope_view_alias_command');for(const key of ['expected_catalog_fingerprint','expected_view_membership_fingerprint','expected_canonical_membership_fingerprint'] as const)expect(()=>assertScopeViewAliasPreviewMatches({...valid,[key]:'0'.repeat(64)},p)).toThrow('scope_view_alias_preview_stale');expect(()=>assertScopeViewAliasPreviewMatches({...valid,expected_canonical_scope_revision:1},p)).toThrow('scope_view_alias_preview_stale');});
  it('rejects redundant roots, foreign view roots and malformed catalog fields instead of silently filtering them',async()=>{const f=await fixture();await expect(previewScopeViewAlias(f.context,'large_project',large,f.c,f.owners)).rejects.toThrow('alias_redundant_canonical_root');f.c.projects[0].organization_id=foreign;await expect(previewScopeViewAlias(f.context,'project',a,f.c,f.owners)).rejects.toThrow();const g=await fixture();await expect(previewScopeViewAlias(g.context,'project',a,{...g.c,actor_id:a},g.owners)).rejects.toThrow('invalid_alias_shared_catalog');g.c.packing_projects[0]=({...g.c.packing_projects[0],deleted_at:null} as unknown as typeof g.c.packing_projects[0]);await expect(previewScopeViewAlias(g.context,'project',a,g.c,g.owners)).rejects.toThrow('invalid_alias_catalog_row');});
});
