import {describe,it,expect} from 'vitest';
import {buildProjectScopeMembership,projectScopeMembershipFingerprint,validateProjectScopeEnrollment,type ScopeServerCatalog} from './canonical-project-scope.ts';
const org='11111111-1111-4111-8111-111111111111',foreign='99999999-9999-4999-8999-999999999999';
const project='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',project2='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',large='cccccccc-cccc-4ccc-8ccc-cccccccccccc',large2='dddddddd-dddd-4ddd-8ddd-dddddddddddd',packing='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',join='ffffffff-ffff-4fff-8fff-ffffffffffff',join2='12121212-1212-4212-8212-121212121212';
function catalog():ScopeServerCatalog{return {projects:[{id:project,organization_id:org,booking_id:'Legacy-Order-42',deleted_at:null},{id:project2,organization_id:org,booking_id:'Legacy-Order-42',deleted_at:null}],large_projects:[{id:large,organization_id:org,primary_booking_id:'Legacy-Order-42',deleted_at:null}],packing_projects:[{id:packing,organization_id:org,booking_id:'Legacy-Order-42',large_project_id:large,status:'delivered'}],bookings:[{id:'Legacy-Order-42',organization_id:org,large_project_id:null}],large_project_bookings:[{id:join,organization_id:org,large_project_id:large,booking_id:'Legacy-Order-42'}],packing_project_bookings:[{id:join2,organization_id:org,packing_id:packing,booking_id:'Legacy-Order-42'}],allowed_packing_statuses:['delivered']};}
describe('membership-only canonical Operations scope',()=>{
  it('captures multiple distinct project leaves and one exact legacy text booking without inventing canonical IDs or money',()=>{const result=buildProjectScopeMembership(org,'large_project',large,catalog());expect(result.source_project_ids).toEqual([project,project2]);expect(result.local_booking_ids).toEqual(['Legacy-Order-42']);expect(result.relationships).toHaveLength(3);expect(result.economic_mapping).toBe('unavailable');expect(Object.hasOwn(result,'currency')).toBe(false);});
  it('captures root itself for a genuine internal project without fabricating a booking',()=>{const c=catalog();c.projects[0].booking_id=null;const result=buildProjectScopeMembership(org,'project',project,c);expect(result.source_project_ids).toEqual([project]);expect(result.local_booking_ids).toEqual([]);expect(result.relationships).toEqual([]);});
  it('canonicalizes UUID identity but preserves local text IDs case and source row order independence',async()=>{const c=catalog();const a=buildProjectScopeMembership(org,'large_project',large,c);c.projects.reverse();c.large_projects[0].id=large.toUpperCase();c.large_project_bookings[0].large_project_id=large.toUpperCase();const b=buildProjectScopeMembership(org.toUpperCase(),'large_project',large.toUpperCase(),c);expect(await projectScopeMembershipFingerprint(a)).toBe(await projectScopeMembershipFingerprint(b));expect(b.local_booking_ids).toEqual(['Legacy-Order-42']);c.projects.pop();expect(await projectScopeMembershipFingerprint(buildProjectScopeMembership(org,'large_project',large,c))).not.toBe(await projectScopeMembershipFingerprint(a));});
  it('never promotes a mirror-only large membership or a primary pointer outside the master join',()=>{const c=catalog();c.bookings.push({id:'unmapped-legacy',organization_id:org,large_project_id:large});expect(()=>buildProjectScopeMembership(org,'large_project',large,c)).toThrow('scope_legacy_mirror_without_master');c.bookings.pop();c.large_projects[0].primary_booking_id='missing-primary';expect(()=>buildProjectScopeMembership(org,'large_project',large,c)).toThrow('scope_primary_booking_not_member');});
  it('rejects ambiguous multiple live large masters but retains a deleted historical parent as noncurrent evidence',()=>{const c=catalog();c.large_projects.push({id:large2,organization_id:org,primary_booking_id:null,deleted_at:null});c.large_project_bookings.push({id:join2,organization_id:org,large_project_id:large2,booking_id:'Legacy-Order-42'});expect(()=>buildProjectScopeMembership(org,'large_project',large,c)).toThrow('scope_ambiguous_live_large_parents');c.large_projects[1].deleted_at='2026-10-02T00:00:00Z';expect(buildProjectScopeMembership(org,'large_project',large,c).local_booking_ids).toEqual(['Legacy-Order-42']);});
  it('fails closed on tenant inconsistencies in roots, source leaves, joins and local bookings',()=>{for(const table of ['projects','large_projects','bookings','large_project_bookings'] as const){const c=catalog();c[table][0].organization_id=foreign;expect(()=>buildProjectScopeMembership(org,'large_project',large,c)).toThrow();}const c=catalog();c.large_projects[0].deleted_at='2026-10-02';expect(()=>buildProjectScopeMembership(org,'large_project',large,c)).toThrow('scope_large_project_missing_or_foreign');});
  it('validates packing explicit status and current same-tenant parent master subset without an invented deleted_at',()=>{const c=catalog();const result=buildProjectScopeMembership(org,'packing_project',packing,c);expect(result.root_evidence.packing_parent_id).toBe(large);expect(result.source_project_ids).toEqual([project,project2]);c.allowed_packing_statuses=[];expect(()=>buildProjectScopeMembership(org,'packing_project',packing,c)).toThrow('scope_packing_missing_or_unenrolled');c.allowed_packing_statuses=['delivered'];c.large_projects[0].deleted_at='2026-10-02';expect(()=>buildProjectScopeMembership(org,'packing_project',packing,c)).toThrow('scope_packing_parent_unavailable');c.large_projects[0].deleted_at=null;c.large_project_bookings=[];expect(()=>buildProjectScopeMembership(org,'packing_project',packing,c)).toThrow('scope_packing_booking_not_parent_member');});
  it('rejects a packing direct pointer conflicting with complete join membership',()=>{const c=catalog();c.packing_projects[0].booking_id='different-pointer';expect(()=>buildProjectScopeMembership(org,'packing_project',packing,c)).toThrow('scope_packing_direct_join_conflict');});
  it('rejects duplicate master rows rather than silently deduplicating unknown source records',()=>{const c=catalog();c.large_project_bookings.push({...c.large_project_bookings[0],id:join2});expect(()=>buildProjectScopeMembership(org,'large_project',large,c)).toThrow('duplicate_scope_relationship');});
  it('rejects duplicate master edges for project and packing roots and hashes the parent join identity',async()=>{for(const kind of ['project','packing_project'] as const){const c=catalog();c.large_project_bookings.push({...c.large_project_bookings[0],id:join2});expect(()=>buildProjectScopeMembership(org,kind,kind==='project'?project:packing,c)).toThrow('duplicate_scope_relationship');}const c=catalog(),before=await projectScopeMembershipFingerprint(buildProjectScopeMembership(org,'packing_project',packing,c));c.large_project_bookings[0].id=join2;expect(await projectScopeMembershipFingerprint(buildProjectScopeMembership(org,'packing_project',packing,c))).not.toBe(before);});
  it('sorts legacy supplementary and BMP text IDs by UTF8 bytes, preserving the original characters',()=>{const c=catalog();c.bookings.push({id:'\u{10000}',organization_id:org,large_project_id:null},{id:'\uE000',organization_id:org,large_project_id:null});c.large_project_bookings.push({id:join2,organization_id:org,large_project_id:large,booking_id:'\u{10000}'},{id:'34343434-3434-4343-8343-343434343434',organization_id:org,large_project_id:large,booking_id:'\uE000'});expect(buildProjectScopeMembership(org,'large_project',large,c).local_booking_ids).toEqual(['Legacy-Order-42','\uE000','\u{10000}']);});
  it('requires an exact admin-intent command without caller actor/org/money and strict integer revision',()=>{const valid={schema:'operations-project-scope-enroll.v1',economic_scope_id:project.toUpperCase(),root_kind:'large_project',root_id:large.toUpperCase(),expected_revision:0,expected_membership_fingerprint:'a'.repeat(64),idempotency_key:'fixture-enrollment',reason:'Explicitly reviewed complete membership'};expect(validateProjectScopeEnrollment(valid).root_id).toBe(large);for(const changed of [{...valid,actor_id:project},{...valid,organization_id:org},{...valid,expected_revision:'0'},{...valid,expected_revision:0.5},{...valid,expected_revision:Number.MAX_SAFE_INTEGER},{...valid,root_id:[large]},{...valid,reason:' '},{...valid,reason:'\tLeading whitespace'},{...valid,expected_membership_fingerprint:['a'.repeat(64)]}])expect(()=>validateProjectScopeEnrollment(changed)).toThrow('invalid_project_scope_enrollment');});
});
