import { describe, expect, it } from "vitest";
import { createHmac } from "node:crypto";
import fixture from "./__fixtures__/cateringAllocationDelivery.json" with {
  type: "json",
};
import {
  type CateringAllocationClaim,
  cateringAllocationJsonRequest,
  dispatchCateringAllocationClaim,
} from "./catering-allocation-finance-transport.ts";
// Raw body/capture generated by actual scoped authority+capture SQL rehearsal.
// Lease owner/token are explicit isolated controls, not live lease/provider proof.
const claim: CateringAllocationClaim = fixture;
const config = {
  enabled: true,
  endpoint: claim.endpoint_url,
  keyId: claim.key_id,
  secret: "isolated-v2-only-signing-key-at-least32",
};
function receipt(overrides: Record<string, unknown> = {}) {
  return {
    schema: "operations-catering-receipt.v2",
    outcome: "accepted",
    source_organization_id: claim.organization_id,
    source_stream_id: claim.source_stream_id,
    requested_source_revision: claim.source_revision,
    applied_source_revision: claim.source_revision,
    current_source_revision: claim.source_revision,
    request_body_sha256: claim.body_sha256,
    snapshot_receipt_id: "96000000-0000-4000-8000-000000000060",
    snapshot_fingerprint: claim.body_sha256,
    receipt_id: "96000000-0000-4000-8000-000000000061",
    destination_organization_id: claim.destination_organization_id,
    shadow_only: true,
    ...overrides,
  };
}
describe("immutable allocation-v2 captured send", () => {
  it("sends actual captured bytes with dedicated HMAC and binds receipt", async () => {
    const result = await dispatchCateringAllocationClaim(
      claim,
      config,
      async (url, init) => {
        expect(String(url)).toBe(claim.endpoint_url);
        expect(init?.redirect).toBe("error");
        expect(init?.body).toBe(claim.raw_body);
        const h = new Headers(init?.headers),
          stamp = h.get("x-eventflow-timestamp"),
          nonce = h.get("x-eventflow-nonce");
        const expected = createHmac("sha256", config.secret).update(
          [
            "POST",
            "operations-catering-allocation-cost-receive",
            "operations-catering-delivery.v2",
            config.keyId,
            stamp,
            nonce,
            claim.raw_body,
          ].join("\n"),
        ).digest("hex");
        expect(h.get("x-eventflow-signature")).toBe("v2=" + expected);
        expect(JSON.parse(claim.raw_body).snapshot.amount_minor).toBe(52502);
        return Response.json(receipt());
      },
    );
    expect(result).toEqual({ outcome: "delivered", receipt: receipt() });
  });
  it("blocks disabled/changed capture or original native route without sending", async () => {
    for (
      const [q, c] of [[claim, { ...config, enabled: false }], [{
        ...claim,
        raw_body: claim.raw_body + " ",
      }, config], [{
        ...claim,
        allocation_event_id: "96000000-0000-4000-8000-000000000199",
      }, config], [claim, {
        ...config,
        endpoint: config.endpoint.replace("allocation-", ""),
      }], [claim, { ...config, keyId: "different-key" }]] as [
        CateringAllocationClaim,
        typeof config,
      ][]
    ) {
      let calls = 0;
      const result = await dispatchCateringAllocationClaim(q, c, async () => {
        calls++;
        throw new Error();
      });
      expect(calls).toBe(0);
      expect(result).toEqual({
        outcome: "blocked",
        error: "catering_allocation_finance_capture_or_configuration_invalid",
      });
    }
  });
  it("older-purpose/tenant/hash/accepted-current receipts cannot finish a delivery", async () => {
    for (
      const change of [
        { schema: "operations-catering-receipt.v1" },
        {
          source_organization_id:
            JSON.parse(claim.raw_body).snapshot.source_organization_id,
        },
        { snapshot_fingerprint: "a".repeat(64) },
        { current_source_revision: claim.source_revision + 1 },
        { receipt_id: [receipt().receipt_id] },
        { extra: true },
      ]
    ) {
      expect(
        await dispatchCateringAllocationClaim(
          claim,
          config,
          async () => Response.json(receipt(change)),
        ),
      )
        .toEqual({
          outcome: "retry",
          error: "catering_allocation_finance_ack_unknown",
        });
    }
  });
  it("distinguishes historical replay from genuine newer stale supersession", async () => {
    const replay = receipt({
      outcome: "replayed",
      current_source_revision: claim.source_revision + 1,
    });
    expect(
      await dispatchCateringAllocationClaim(
        claim,
        config,
        async () => Response.json(replay),
      ),
    ).toEqual({ outcome: "delivered", receipt: replay });
    const stale = receipt({
      outcome: "stale",
      applied_source_revision: claim.source_revision + 1,
      current_source_revision: claim.source_revision + 1,
      snapshot_fingerprint: "b".repeat(64),
    });
    expect(
      await dispatchCateringAllocationClaim(
        claim,
        config,
        async () => Response.json(stale, { status: 409 }),
      ),
    ).toEqual({ outcome: "superseded", receipt: stale });
    expect(
      await dispatchCateringAllocationClaim(
        claim,
        config,
        async () => Response.json(stale),
      ),
    ).toEqual({
      outcome: "retry",
      error: "catering_allocation_finance_ack_unknown",
    });
  });
  it("fresh security nonce signs the same captured retry body", async () => {
    const nonces: string[] = [], bodies: unknown[] = [];
    const peer: typeof fetch = async (_url, init) => {
      nonces.push(new Headers(init?.headers).get("x-eventflow-nonce")!);
      bodies.push(init?.body);
      throw new Error("private peer");
    };
    for (let i = 0; i < 2; i++) {
      expect(await dispatchCateringAllocationClaim(claim, config, peer))
        .toEqual({
          outcome: "retry",
          error: "catering_allocation_finance_ack_unknown",
        });
    }
    expect(nonces[0]).not.toBe(nonces[1]);
    expect(bodies).toEqual([claim.raw_body, claim.raw_body]);
  });
  it("never returns peer diagnostics in denied or retry states", async () => {
    for (const status of [403, 422, 500]) {
      expect(
        await dispatchCateringAllocationClaim(
          claim,
          config,
          async () => Response.json({ private: "body" }, { status }),
        ),
      )
        .toEqual({
          outcome: status === 500 ? "retry" : "blocked",
          error: "catering_allocation_finance_http_" + status,
        });
    }
  });
});
describe("allocation-v2 response work bound", () => {
  it("empty microtask chunk flood is finite and cancelled without awaiting cancellation", async () => {
    let reads = 0, cancelled = false;
    await expect(
      cateringAllocationJsonRequest(
        config.endpoint,
        {},
        async () =>
          new Response(
            new ReadableStream({
              pull(c) {
                reads++;
                c.enqueue(new Uint8Array());
              },
              cancel() {
                cancelled = true;
                return new Promise(() => {});
              },
            }),
          ),
        async () => true,
        1000,
      ),
    ).rejects.toThrow("backend_too_many_chunks");
    expect(reads).toBeLessThanOrEqual(4098);
    expect(cancelled).toBe(true);
  });
  it("an abort-ignoring fetch has bounded deadline and its late response is cancelled", async () => {
    let resolve: ((r: Response) => void) | undefined,
      cancelled = false,
      inspections = 0;
    const pending = cateringAllocationJsonRequest(
      config.endpoint,
      {},
      () =>
        new Promise((r) => {
          resolve = r;
        }),
      async () => {
        inspections++;
        return true;
      },
      10,
    );
    await expect(pending).rejects.toThrow("backend_timeout");
    resolve?.(
      new Response(
        new ReadableStream({
          cancel() {
            cancelled = true;
          },
        }),
      ),
    );
    await new Promise((r) => setTimeout(r, 0));
    expect(cancelled).toBe(true);
    expect(inspections).toBe(0);
  });
  it("bounds real UTF8 receipt bytes and forbids redirects", async () => {
    await expect(
      cateringAllocationJsonRequest(
        config.endpoint,
        {},
        async (_url, init) => {
          expect(init?.redirect).toBe("error");
          return new Response("x".repeat(16385));
        },
        async () => true,
        1000,
      ),
    ).rejects.toThrow("backend_too_large");
  });
});
