import {describe,it,expect} from 'vitest';import{projectLocalInvoiceKernelEvidence,validateLocalInvoiceKernelEvidence,type LocalInvoiceKernelEvidence}from'./local-invoice-obligation-kernel-evidence.ts';
const id='11111111-1111-4111-8111-111111111111';const evidence=():LocalInvoiceKernelEvidence=>({schema_version:'operations-invoice-obligation-kernel-evidence.v1',state:'captured',authority_scope:'local_project_only',source_currentness:'saved_receiver_heads_only',organization_id:id,project_id:id,obligation_id:id,category_coverage:'unavailable',source_coverage:'unavailable',as_of:'2026-10-02T00:00:00Z',baseline:{event_id:id,revision:1,fingerprint:'a'.repeat(64),evidence_basis:'operations_manual',currency:'SEK',category:'supplier',cost_basis:'invoice',estimate_minor:1000000,committed_minor:null},sources:[{source_anchor:'b'.repeat(64),binding_event_id:id,source_organization_id:id,invoice_id:id,source_snapshot_id:id,source_economic_revision:1,source_economic_fingerprint:'c'.repeat(64),source_raw_sha256:'d'.repeat(64),resolved:true,reason:null,current_snapshot_id:id,current_raw_sha256:'d'.repeat(64),status:'preliminary',amount_minor:540000,policy_state:'current',policy_event_id:id,policy_revision:1,policy_fingerprint:'e'.repeat(64),replaces_estimate_minor:700000,consumes_commitment_minor:null}],diagnostics:[] as string[],credit_eligible:false,shadow_only:true,eac_minor:null,remaining_minor:null});
describe('local invoice evidence to frozen Operations kernel',()=>{
 it('copies partial invoice and planned variance while preserving unknown commitment/EAC',()=>{const p=projectLocalInvoiceKernelEvidence(evidence());expect(p.known_captured_cost_minor).toBe(540000);expect(p.kernel_input?.sources[0].replaces_estimate_minor).toBe(700000);expect(p.kernel_result?.commitment_remaining_minor).toBeNull();expect(p.kernel_result?.coverage).toBe('unavailable');expect(p.eac_minor).toBeNull();});
 it('missing policy retains actual cost and nullable replacement',()=>{const e=evidence();Object.assign(e.sources[0],{policy_state:'missing',policy_event_id:null,policy_revision:null,policy_fingerprint:null,replaces_estimate_minor:null});const p=projectLocalInvoiceKernelEvidence(e);expect(p.known_captured_cost_minor).toBe(540000);expect(p.diagnostics).toContain('unavailable_source_policy:'+'b'.repeat(64));});
 it('empty or excluded sources never become project actual zero',()=>{const e=evidence();e.sources=[];expect(projectLocalInvoiceKernelEvidence(e).known_captured_cost_minor).toBeNull();const f=evidence();Object.assign(f.sources[0],{resolved:false,reason:'changed_source',current_snapshot_id:null,current_raw_sha256:null,status:null,amount_minor:null,policy_state:'stale',replaces_estimate_minor:null});const p=projectLocalInvoiceKernelEvidence(f);expect(p.known_captured_cost_minor).toBeNull();expect(p.excluded_source_anchors).toEqual(['b'.repeat(64)]);});
 it('keeps every excluded permanent anchor alongside a partial known cost',()=>{const e=evidence();for(const anchor of ['f'.repeat(64),'0'.repeat(64)])e.sources.push({...e.sources[0],source_anchor:anchor,resolved:false,reason:'changed_source',current_snapshot_id:null,current_raw_sha256:null,status:null,amount_minor:null,policy_state:'stale',replaces_estimate_minor:null} as typeof e.sources[0]);const p=projectLocalInvoiceKernelEvidence(e);expect(p.known_captured_cost_minor).toBe(540000);expect(p.excluded_source_anchors).toEqual(['f'.repeat(64),'0'.repeat(64)]);expect(p.kernel_input?.sources).toHaveLength(1);for(const anchor of p.excluded_source_anchors)expect(p.diagnostics).toContain('excluded_source:'+anchor+':changed_source');});
 it('preserves an independently unknown estimate without inferring it from invoice money',()=>{const e=evidence();Object.assign(e.baseline,{estimate_minor:null});Object.assign(e.sources[0],{replaces_estimate_minor:null});const p=projectLocalInvoiceKernelEvidence(e);expect(p.known_captured_cost_minor).toBe(540000);expect(p.kernel_input?.estimate_minor).toBeNull();expect(p.kernel_result?.coverage).toBe('unavailable');expect(p.eac_minor).toBeNull();});
 it('rejects stale policy price, duplicate anchors, unknown-key pricing and unsafe amounts',()=>{const e=evidence();e.sources[0].policy_state='stale';expect(()=>projectLocalInvoiceKernelEvidence(e)).toThrow();const f=evidence();f.sources.push({...f.sources[0]});expect(()=>projectLocalInvoiceKernelEvidence(f)).toThrow();expect(()=>validateLocalInvoiceKernelEvidence({...evidence(),paid:true})).toThrow();const u=evidence();u.sources[0].amount_minor=Number.MAX_SAFE_INTEGER+1;expect(()=>projectLocalInvoiceKernelEvidence(u)).toThrow();});
 it('unsupported time/Catering basis is visible and never replaced by invoice math',()=>{const e=evidence();e.state='unsupported_basis';e.baseline.cost_basis='time';e.sources=[];e.diagnostics=['unsupported_cost_basis'];const p=projectLocalInvoiceKernelEvidence(e);expect(p.kernel_result).toBeNull();expect(p.known_captured_cost_minor).toBeNull();expect(p.eac_minor).toBeNull();});
 it('requires a timestamp string rather than a date keyword or coercible value',()=>{for(const as_of of ['today','2026-10-02','2026-02-30T12:00:00Z','2026-02-29T12:00:00Z',123,['2026-10-02T00:00:00Z']])expect(()=>validateLocalInvoiceKernelEvidence({...evidence(),as_of})).toThrow();});
 it('accepts genuine leap day and a calendar-valid numeric offset without rewriting source time',()=>{for(const as_of of ['2024-02-29T12:00:00Z','2026-10-02T00:00:00+23:00'])expect(validateLocalInvoiceKernelEvidence({...evidence(),as_of}).as_of).toBe(as_of);});
 it('does not accept complete coverage or direct credit eligibility',()=>{expect(()=>validateLocalInvoiceKernelEvidence({...evidence(),source_coverage:'complete'})).toThrow();expect(()=>validateLocalInvoiceKernelEvidence({...evidence(),credit_eligible:true})).toThrow();});
});
