import {describe,it,expect} from 'vitest';
import {validateBookingCommercialReadRequest,validateBookingCommercialReadResponse,bookingCommercialEvidenceFingerprint,type BookingCommercialReadResponse} from './project-booking-commercial-read.ts';
function request(){return {schema_version:'operations-booking-commercial-read.v1',operations_organization_id:'11111111-1111-4111-8111-111111111111',economic_scope_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',scope_revision:1,finance_organization_id:'22222222-2222-4222-8222-222222222222',finance_project_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',booking_source_organization_id:'33333333-3333-4333-8333-333333333333',booking_source_id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',requested_source_sequence:null};}
describe('scoped immutable Booking commercial read intent',()=>{
 it('keeps distinct tenant identities and latest-received versus explicit historical source selection',()=>{const latest=validateBookingCommercialReadRequest(request());expect(latest.requested_source_sequence).toBe(null);const historical=validateBookingCommercialReadRequest({...request(),requested_source_sequence:29});expect(historical.requested_source_sequence).toBe(29);expect(historical.booking_source_organization_id).not.toBe(historical.finance_organization_id);});
 it('normalizes UUID spelling without inferring a local text Booking identity',()=>{const r=validateBookingCommercialReadRequest({...request(),booking_source_id:request().booking_source_id.toUpperCase()});expect(r.booking_source_id).toBe(request().booking_source_id);expect(()=>validateBookingCommercialReadRequest({...request(),booking_source_id:'Legacy-Order-42'})).toThrow('invalid_booking_commercial_read_request');});
 it('requires exact request keys, with no caller money or arbitrary organization/actor envelope',()=>{for(const field of ['amount_minor','actor_id','local_booking_id','upstream_currentness'])expect(()=>validateBookingCommercialReadRequest({...request(),[field]:0})).toThrow();const missing=request() as Record<string,unknown>;delete missing.scope_revision;expect(()=>validateBookingCommercialReadRequest(missing)).toThrow();});
 it('requires strict positive safe integer revisions with an explicitly present nullable selection',()=>{for(const value of ['1',0,-1,1.5,Number.MAX_SAFE_INTEGER+1,null])expect(()=>validateBookingCommercialReadRequest({...request(),scope_revision:value})).toThrow();for(const value of ['1',0,-1,1.5,Number.MAX_SAFE_INTEGER+1,undefined])expect(()=>validateBookingCommercialReadRequest({...request(),requested_source_sequence:value})).toThrow();});
 it('rejects coerced array identities, surrounding whitespace, wrong schema and nonobjects',()=>{for(const value of [null,[],{...request(),finance_project_id:[request().finance_project_id]},{...request(),finance_project_id:' '+request().finance_project_id},{...request(),schema_version:'operations-personnel-cost-v1'}])expect(()=>validateBookingCommercialReadRequest(value)).toThrow('invalid_booking_commercial_read_request');});
});

async function response():Promise<BookingCommercialReadResponse>{const {schema_version,...scope}=validateBookingCommercialReadRequest(request());const result:BookingCommercialReadResponse={...scope,schema_version:'finance-booking-commercial-evidence-read.v1',state:'received',receipt_id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',source_sequence:77,commercial_snapshot_id:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',commercial_revision:3,currency:'SEK',invoiceable_net_minor:45000,invoiceable_vat_minor:11250,lifecycle_status:'confirmed',source_disappeared:false,rows:[{source_row_id:'product-row',source_row_revision:77,net_minor:50000,vat_minor:12500,quantity:'1.00'},{source_row_id:'booking-approved-adjustment:cccccccc-cccc-4ccc-8ccc-cccccccccccc',source_row_revision:77,net_minor:-5000,vat_minor:-1250,quantity:'1'}],latest_received_sequence:77,is_latest_received:true,observed_at:'2026-10-02T01:00:00.000000+00:00',received_at:'2026-10-02T01:00:01+00:00',as_of:'2026-10-02T01:01:00Z',upstream_currentness:'unverified',evidence_fingerprint:null};result.evidence_fingerprint=await bookingCommercialEvidenceFingerprint(result);return result;}
describe('copied immutable commercial response',()=>{
 it('accepts exact scoped saved evidence including signed adjustments and original quantity scale, without pricing or VAT recomputation',async()=>{const r=await response();expect(await validateBookingCommercialReadResponse(r,validateBookingCommercialReadRequest(request()))).toEqual(r);expect(r.rows[0].quantity).toBe('1.00');expect(r.rows[1].net_minor).toBe(-5000);expect(r.upstream_currentness).toBe('unverified');});
 it('retains the same immutable hash for historical evidence while latest received/as_of/selection change',async()=>{const r=await response(),before=r.evidence_fingerprint;r.requested_source_sequence=77;r.latest_received_sequence=88;r.is_latest_received=false;r.as_of='2026-10-02T02:00:00Z';expect(await bookingCommercialEvidenceFingerprint(r)).toBe(before);await expect(validateBookingCommercialReadResponse(r,validateBookingCommercialReadRequest({...request(),requested_source_sequence:77}))).resolves.toEqual(r);await expect(validateBookingCommercialReadResponse({...r,requested_source_sequence:null},validateBookingCommercialReadRequest(request()))).rejects.toThrow('invalid_booking_commercial_saved_evidence');});
 it('keeps copied monetary rows when the source disappeared and records the new receipt/source/commercial revisions separately',async()=>{const r=await response();r.state='source_disappeared';r.source_disappeared=true;r.lifecycle_status='cancelled';r.source_sequence=99;r.latest_received_sequence=99;r.commercial_revision=4;r.evidence_fingerprint=await bookingCommercialEvidenceFingerprint(r);const accepted=await validateBookingCommercialReadResponse(r,validateBookingCommercialReadRequest(request()));expect(accepted.invoiceable_net_minor).toBe(45000);expect(accepted.rows[0].source_row_revision).toBe(77);await expect(validateBookingCommercialReadResponse({...r,lifecycle_status:'confirmed'},validateBookingCommercialReadRequest(request()))).rejects.toThrow('invalid_booking_commercial_saved_evidence');});
 it('represents missing source evidence by null money/proof and never an invented zero',async()=>{const r=await response();const missing:BookingCommercialReadResponse={...r,state:'no_evidence',receipt_id:null,source_sequence:null,commercial_snapshot_id:null,commercial_revision:null,currency:null,invoiceable_net_minor:null,invoiceable_vat_minor:null,lifecycle_status:null,source_disappeared:null,rows:[],latest_received_sequence:null,is_latest_received:false,observed_at:null,received_at:null,evidence_fingerprint:null};await expect(validateBookingCommercialReadResponse(missing,validateBookingCommercialReadRequest(request()))).resolves.toEqual(missing);await expect(validateBookingCommercialReadResponse({...missing,invoiceable_net_minor:0},validateBookingCommercialReadRequest(request()))).rejects.toThrow('unavailable_booking_commercial_evidence_has_values');await expect(validateBookingCommercialReadResponse({...missing,latest_received_sequence:88},validateBookingCommercialReadRequest(request()))).rejects.toThrow('unavailable_booking_commercial_evidence_has_values');missing.requested_source_sequence=17;missing.latest_received_sequence=88;await expect(validateBookingCommercialReadResponse(missing,validateBookingCommercialReadRequest({...request(),requested_source_sequence:17}))).resolves.toEqual(missing);});
 it('rejects scope/tenant/selection drift, wrong source types and unknown/extra response keys',async()=>{const r=await response(),expected=validateBookingCommercialReadRequest(request());for(const changed of [{...r,finance_organization_id:r.booking_source_organization_id},{...r,booking_source_id:[r.booking_source_id]},{...r,scope_revision:2},{...r,requested_source_sequence:77}])await expect(validateBookingCommercialReadResponse(changed,expected)).rejects.toThrow('booking_commercial_read_scope_mismatch');for(const changed of [{...r,recipient:{email:'forbidden'}},{...r,upstream_currentness:'verified'},{...r,as_of:'2026-02-30T00:00:00Z'}])await expect(validateBookingCommercialReadResponse(changed,expected)).rejects.toThrow('invalid_booking_commercial_read_response');});
 it('rejects copied header/line inconsistency, duplicate IDs, malformed decimal/row types and line truncation',async()=>{const r=await response(),expected=validateBookingCommercialReadRequest(request());await expect(validateBookingCommercialReadResponse({...r,invoiceable_net_minor:45001},expected)).rejects.toThrow('booking_commercial_saved_row_totals_mismatch');for(const rows of [[{...r.rows[0],net_minor:'50000'},r.rows[1]],[{...r.rows[0],quantity:'1e0'},r.rows[1]],[{...r.rows[0],quantity:'01.00'},r.rows[1]],[{...r.rows[0],quantity:' 1.00'},r.rows[1]],[{...r.rows[0],source_row_id:['product-row']},r.rows[1]],r.rows.map(row=>({...row,source_row_id:'duplicate'})),[{...r.rows[0],extra_key:1},r.rows[1]]])await expect(validateBookingCommercialReadResponse({...r,rows},expected)).rejects.toThrow('invalid_booking_commercial_saved_row');await expect(validateBookingCommercialReadResponse({...r,rows:Array.from({length:1001},()=>r.rows[0])},expected)).rejects.toThrow('invalid_booking_commercial_read_response');});
 it('binds exact row order, quantity text and saved receipt to the fingerprint',async()=>{const r=await response(),expected=validateBookingCommercialReadRequest(request());for(const changed of [{...r,rows:[...r.rows].reverse()},{...r,rows:[{...r.rows[0],quantity:'1'},r.rows[1]]},{...r,receipt_id:'ffffffff-ffff-4fff-8fff-ffffffffffff'}])await expect(validateBookingCommercialReadResponse(changed,expected)).rejects.toThrow('booking_commercial_evidence_fingerprint_mismatch');});
});
