import {describe,it,expect} from 'vitest';
import {createHmac} from 'node:crypto';
import {readBookingCommercialEvidence,signBookingCommercialRead,type BookingCommercialReadSource} from './project-booking-commercial-read-client.ts';
import {bookingCommercialEvidenceFingerprint,type BookingCommercialReadRequest,type BookingCommercialReadResponse} from './project-booking-commercial-read.ts';
const request:BookingCommercialReadRequest={schema_version:'operations-booking-commercial-read.v1',operations_organization_id:'11111111-1111-4111-8111-111111111111',economic_scope_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',scope_revision:1,finance_organization_id:'22222222-2222-4222-8222-222222222222',finance_project_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',booking_source_organization_id:'33333333-3333-4333-8333-333333333333',booking_source_id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',requested_source_sequence:null};
const source:BookingCommercialReadSource={enabled:true,endpoint_url:'https://finance.example.test/functions/v1/finance-booking-commercial-evidence-read',key_id:'fixture_read_key',secret:'s'.repeat(32),operations_organization_id:request.operations_organization_id,finance_organization_id:request.finance_organization_id,booking_source_organization_id:request.booking_source_organization_id};
async function evidence():Promise<BookingCommercialReadResponse>{const {schema_version,...scope}=request;const r:BookingCommercialReadResponse={...scope,schema_version:'finance-booking-commercial-evidence-read.v1',state:'received',receipt_id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',source_sequence:77,commercial_snapshot_id:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee',commercial_revision:3,currency:'SEK',invoiceable_net_minor:45000,invoiceable_vat_minor:11250,lifecycle_status:'confirmed',source_disappeared:false,rows:[{source_row_id:'source-product',source_row_revision:77,net_minor:45000,vat_minor:11250,quantity:'1.00'}],latest_received_sequence:77,is_latest_received:true,observed_at:'2026-10-02T00:00:00+00:00',received_at:'2026-10-02T00:00:01+00:00',as_of:'2026-10-02T00:00:02+00:00',upstream_currentness:'unverified',evidence_fingerprint:null};r.evidence_fingerprint=await bookingCommercialEvidenceFingerprint(r);return r;}
describe('purpose-bound read-only HTTPS caller',()=>{
 it('sends exact normalized nine-field body with a dedicated read purpose, fresh nonce and restricted redirect policy',async()=>{const reply=await evidence();let calls=0;const fake:typeof fetch=async(url,init)=>{calls++;expect(String(url)).toBe(source.endpoint_url);expect(init?.method).toBe('POST');expect(init?.redirect).toBe('error');const headers=new Headers(init?.headers),raw=String(init?.body);expect(JSON.parse(raw)).toEqual(request);expect(headers.get('x-eventflow-nonce')).toMatch(/^[A-Za-z0-9_-]{16,128}$/);const text=['POST','finance-booking-commercial-evidence-read','operations-booking-commercial-read.v1',source.key_id,headers.get('x-eventflow-timestamp'),headers.get('x-eventflow-nonce'),raw].join('\n');expect(headers.get('x-eventflow-signature')).toBe('v1='+createHmac('sha256',source.secret).update(text).digest('hex'));return new Response(JSON.stringify(reply),{headers:{'content-type':'application/json'}});};expect(await readBookingCommercialEvidence(request,source,{fetchImpl:fake})).toEqual(reply);expect(calls).toBe(1);});
 it('denies disabled, wrong scope/tenant, HTTP, credentials and route/config before any outbound request',async()=>{let calls=0;const fake:typeof fetch=async()=>{calls++;return new Response('{}');};for(const changed of [{...source,enabled:false},{...source,finance_organization_id:request.booking_source_organization_id},{...source,operations_organization_id:null},{...source,endpoint_url:source.endpoint_url.replace('https:','http:')},{...source,endpoint_url:source.endpoint_url+'?tenant=unsafe'},{...source,endpoint_url:source.endpoint_url.replace('finance.example.test','user:password@finance.example.test')},{...source,endpoint_url:source.endpoint_url.replace('evidence-read','personnel-cost-receive')},{...source,secret:'short'},{...source,key_id:'bad\nkey'}])await expect(readBookingCommercialEvidence(request,changed as BookingCommercialReadSource,{fetchImpl:fake})).rejects.toThrow();expect(calls).toBe(0);});
 it('maps disabled/auth/scope/source/schema failures without exposing raw peer errors',async()=>{for(const [status,code] of [[503,'source_unavailable'],[401,'source_authentication_failed'],[403,'source_forbidden'],[422,'invalid_source_response']] as const)await expect(readBookingCommercialEvidence(request,source,{fetchImpl:async()=>new Response('SECRET peer detail',{status})})).rejects.toMatchObject({code,message:code});await expect(readBookingCommercialEvidence(request,source,{fetchImpl:async()=>{throw new Error('private network hostname');}})).rejects.toMatchObject({code:'source_unavailable'});});
 it('requires JSON, bounded response bytes and exact immutable proof',async()=>{const r=await evidence();for(const response of [new Response(JSON.stringify(r),{headers:{'content-type':'text/plain'}}),new Response(JSON.stringify(r),{headers:{'content-type':'application/json','content-length':String(256*1024+1)}}),new Response(' '.repeat(256*1024+1),{headers:{'content-type':'application/json'}}),new Response(JSON.stringify({...r,evidence_fingerprint:'f'.repeat(64)}),{headers:{'content-type':'application/json'}}),new Response('{broken',{headers:{'content-type':'application/json'}})])await expect(readBookingCommercialEvidence(request,source,{fetchImpl:async()=>response})).rejects.toMatchObject({code:'invalid_source_response'});});
 it('bounds fetch which ignores AbortSignal, and refuses cancelled-stream EOF as successful timeout completion',async()=>{await expect(readBookingCommercialEvidence(request,source,{timeoutMs:10,fetchImpl:async()=>await new Promise<Response>(()=>{})})).rejects.toMatchObject({code:'timeout'});let cancelled=false;const stream=new ReadableStream<Uint8Array>({pull:()=>new Promise<void>(()=>{}),cancel(){cancelled=true;}});await expect(readBookingCommercialEvidence(request,source,{timeoutMs:10,fetchImpl:async()=>new Response(stream,{headers:{'content-type':'application/json'}})})).rejects.toMatchObject({code:'timeout'});expect(cancelled).toBe(true);});
 it('never accepts an ingest purpose in place of the dedicated read signature',async()=>{const raw=JSON.stringify(request),nonce='synthetic_nonce_123456',timestamp='1790899200',signature=await signBookingCommercialRead(source.key_id,source.secret,timestamp,nonce,raw);const wrong=createHmac('sha256',source.secret).update(['POST','operations-personnel-cost-receive','operations-personnel-cost-v1',source.key_id,timestamp,nonce,raw].join('\n')).digest('hex');expect(signature).not.toBe('v1='+wrong);});
 it('rejects nonstring arguments in the exported signer before regex/TextEncoder coercion',async()=>{const args=[source.key_id,source.secret,'1790899200','synthetic_nonce_123456',JSON.stringify(request)];for(let index=0;index<args.length;index++){const invalid=[...args] as unknown[];invalid[index]=[args[index]];await expect(signBookingCommercialRead(...invalid as [string,string,string,string,string])).rejects.toMatchObject({code:'invalid_authority'});}});
 it('cancels an AbortSignal-ignoring response which arrives after deadline before it starts any stream read',async()=>{let resolveFetch!:(value:Response)=>void,cancelled=false,pulls=0;const pending=new Promise<Response>(resolve=>{resolveFetch=resolve;});await expect(readBookingCommercialEvidence(request,source,{timeoutMs:10,fetchImpl:async()=>pending})).rejects.toMatchObject({code:'timeout'});const stream=new ReadableStream<Uint8Array>({pull(){pulls++;return new Promise<void>(()=>{});},cancel(){cancelled=true;}},{highWaterMark:0});resolveFetch(new Response(stream,{headers:{'content-type':'application/json'}}));await new Promise(resolve=>setTimeout(resolve,0));expect(cancelled).toBe(true);expect(pulls).toBe(0);});
 it('cancels malformed unconsumed response bodies even when no reader was assigned',async()=>{for(const headers of [{'content-type':'text/plain'},{'content-type':'application/json','content-length':String(256*1024+1)}]){let cancelled=false;const body=new ReadableStream<Uint8Array>({cancel(){cancelled=true;}},{highWaterMark:0});await expect(readBookingCommercialEvidence(request,source,{fetchImpl:async()=>new Response(body,{headers})})).rejects.toMatchObject({code:'invalid_source_response'});expect(cancelled).toBe(true);}});
});
