import {describe,it,expect} from 'vitest';
import {invoiceAllocationSourceAnchor,validateInvoiceObligationBindingCommand,validateManualObligationBaselineCommand} from './project-cost-obligation-authority.ts';
const project='55555555-5555-4555-8555-555555555555',obligation='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
const baseline=()=>({schema_version:'operations-obligation-manual-baseline.v1',project_id:project,obligation_id:obligation,expected_revision:0,currency:'SEK',category:'supplier',cost_basis:'invoice',estimate_minor:100000,committed_minor:null,idempotency_key:'synthetic-baseline-one',reason:'Reviewed manual budget, commitment unknown'});
describe('manual Operations obligation authority command',()=>{
 it('preserves explicit unknown commitment and explicit zero without claiming Booking proof',()=>{expect(validateManualObligationBaselineCommand({...baseline(),estimate_minor:0})).toMatchObject({estimate_minor:0,committed_minor:null});});
 it('rejects injected source costs/actor and unsafe or coerced money',()=>{for(const bad of [{...baseline(),actor:'x'},{...baseline(),amount_minor:99},{...baseline(),estimate_minor:'100000'},{...baseline(),committed_minor:-1},{...baseline(),expected_revision:Number.MAX_SAFE_INTEGER}])expect(()=>validateManualObligationBaselineCommand(bad)).toThrow();});
 it('normalizes valid UUID identities while retaining actor-free exact command',()=>{expect(validateManualObligationBaselineCommand({...baseline(),obligation_id:obligation.toUpperCase()})).toMatchObject({obligation_id:obligation});});
 it('binding selectors cannot supply actual source amounts/status or arbitrary ownership',()=>{const value={schema_version:'operations-obligation-invoice-bind.v1',project_id:project,obligation_id:obligation,expected_obligation_revision:1,source_snapshot_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',source_allocation_id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',expected_economic_revision:2,expected_economic_fingerprint:'e'.repeat(64),idempotency_key:'synthetic-binding-one',reason:'Map actual saved invoice allocation'};expect(validateInvoiceObligationBindingCommand(value)).toEqual(value);for(const bad of [{...value,status:'confirmed'},{...value,amount_minor:1},{...value,source_anchor:'e'.repeat(64)},{...value,expected_economic_revision:'2'}])expect(()=>validateInvoiceObligationBindingCommand(bad)).toThrow();});
 it('anchor is case-insensitive only for UUIDs, and binds currency/document/allocation',async()=>{const value={source_organization_id:'11111111-1111-4111-8111-111111111111',invoice_id:obligation,allocation_id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',document_fingerprint:'d'.repeat(64),currency:'SEK'};const a=await invoiceAllocationSourceAnchor(value);expect(a).toMatch(/^[0-9a-f]{64}$/);expect(await invoiceAllocationSourceAnchor({...value,invoice_id:obligation.toUpperCase()})).toBe(a);expect(await invoiceAllocationSourceAnchor({...value,currency:'EUR'})).not.toBe(a);expect(await invoiceAllocationSourceAnchor({...value,document_fingerprint:'e'.repeat(64)})).not.toBe(a);await expect(invoiceAllocationSourceAnchor({...value,currency:['SEK']} as never)).rejects.toThrow();});
});
