import{describe,it,expect}from'vitest';
import{projectScopeInvoiceKernelEvidence,validateScopeInvoiceKernelEvidence,scopeInvoiceInventoryFingerprint,type ScopeInvoiceKernelEvidence,type SavedScopeInvoiceReference}from'./project-scope-invoice-kernel-evidence.ts';
const id=(c:string)=>`${c.repeat(8)}-${c.repeat(4)}-${c.repeat(4)}-${c.repeat(4)}-${c.repeat(12)}`;
async function fixture():Promise<ScopeInvoiceKernelEvidence>{
 const members=['5','7'].map((c,i)=>({project_id:id(c),obligation_id:id(i?'c':'a'),captured_baseline_event_id:id(i?'d':'b'),captured_baseline_revision:1,captured_baseline_fingerprint:'a'.repeat(64),kernel_evidence:{schema_version:'operations-invoice-obligation-kernel-evidence.v1' as const,state:'captured' as const,authority_scope:'local_project_only' as const,source_currentness:'saved_receiver_heads_only' as const,organization_id:id('1'),project_id:id(c),obligation_id:id(i?'c':'a'),category_coverage:'unavailable' as const,source_coverage:'unavailable' as const,as_of:'2026-10-02T00:00:00Z',baseline:{event_id:id(i?'d':'b'),revision:1,fingerprint:'a'.repeat(64),evidence_basis:'operations_manual' as const,currency:'SEK',category:'supplier' as const,cost_basis:'invoice' as const,estimate_minor:1000000,committed_minor:null},sources:[{source_anchor:String(i).repeat(64),binding_event_id:id(i?'3':'2'),source_organization_id:id('9'),invoice_id:id('e'),source_snapshot_id:id('4'),source_economic_revision:1,source_economic_fingerprint:'b'.repeat(64),source_raw_sha256:'c'.repeat(64),resolved:true,reason:null,current_snapshot_id:id('4'),current_raw_sha256:'c'.repeat(64),status:(i?'confirmed':'preliminary') as 'confirmed'|'preliminary',amount_minor:270000,policy_state:'current' as const,policy_event_id:id(i?'8':'6'),policy_revision:1,policy_fingerprint:'d'.repeat(64),replaces_estimate_minor:300000,consumes_commitment_minor:null}],diagnostics:[],credit_eligible:false as const,shadow_only:true as const,eac_minor:null,remaining_minor:null}}));
 const inventory=members.map(m=>{const s=m.kernel_evidence.sources[0];return{source_anchor:s.source_anchor,project_id:m.project_id,obligation_id:m.obligation_id,binding_event_id:s.binding_event_id,source_organization_id:s.source_organization_id,invoice_id:s.invoice_id,source_snapshot_id:s.source_snapshot_id,source_economic_revision:s.source_economic_revision,source_economic_fingerprint:s.source_economic_fingerprint,source_raw_sha256:s.source_raw_sha256,current_snapshot_id:s.current_snapshot_id,current_raw_sha256:s.current_raw_sha256,policy_state:s.policy_state,policy_event_id:s.policy_event_id,policy_revision:s.policy_revision,policy_fingerprint:s.policy_fingerprint,mapping_state:'charging' as const,reason:null};});
 const saved=inventory.map(s=>({source_anchor:s.source_anchor,project_id:s.project_id,obligation_id:s.obligation_id,binding_event_id:s.binding_event_id,source_snapshot_id:s.current_snapshot_id,source_economic_revision:s.source_economic_revision,source_economic_fingerprint:s.source_economic_fingerprint,source_raw_sha256:s.current_raw_sha256,binding_state:'bound_original' as const,policy_state:s.policy_state,policy_event_id:s.policy_event_id,policy_revision:s.policy_revision,policy_fingerprint:s.policy_fingerprint}));
 return{schema_version:'operations-scope-invoice-kernel-evidence.v1',organization_id:id('1'),economic_scope_id:id('f'),scope_snapshot_id:id('a'),scope_revision:1,membership_fingerprint:'e'.repeat(64),composition_snapshot_id:id('b'),composition_revision:1,composition_fingerprint:'f'.repeat(64),root_kind:'large_project',root_id:id('c'),currency:'SEK',membership_currentness:'as_of_graph',source_currentness:'saved_receiver_heads_only',captured_inventory_matches_current:true,captured_inventory_fingerprint:await scopeInvoiceInventoryFingerprint(inventory),as_of:'2026-10-02T00:00:00Z',members,source_inventory:inventory,saved_source_references:saved as SavedScopeInvoiceReference[],diagnostics:[],category_coverage:{personnel:'unavailable',supplier:'unavailable',catering:'unavailable',other:'unavailable'},source_coverage:'unavailable',credit_eligible:false,remaining_minor:null,eac_minor:null,budget_minor:null,shadow_only:true};
}
describe('whole-scope captured invoice kernel projection',()=>{
 it('counts two legitimate allocation portions in the same invoice once, without summing manual baselines',async()=>{const e=await fixture(),p=await projectScopeInvoiceKernelEvidence(e);expect(p.known_captured_invoice_cost_minor).toBe(540000);expect(p.confirmed_captured_invoice_cost_minor).toBe(270000);expect(p.preliminary_captured_invoice_cost_minor).toBe(270000);expect(p.resolved_source_count).toBe(2);expect(p.eac_minor).toBeNull();expect(p.budget_minor).toBeNull();});
 it('accepts a newer explicit policy with saved immutable references distinguished',async()=>{const e=await fixture();for(const s of [e.source_inventory[0],e.members[0].kernel_evidence.sources[0]]){s.policy_revision=2;s.policy_fingerprint='e'.repeat(64);}e.captured_inventory_matches_current=false;e.diagnostics=['captured_inventory_changed'];e.captured_inventory_fingerprint=await scopeInvoiceInventoryFingerprint(e.source_inventory);const p=await projectScopeInvoiceKernelEvidence(e);expect(p.known_captured_invoice_cost_minor).toBe(540000);expect(p.captured_inventory_matches_current).toBe(false);expect(p.eac_minor).toBeNull();});
 it('coequal V2 current metadata changes captured proof without changing valid V1 money',async()=>{const e=await fixture();for(const s of [e.source_inventory[0],e.members[0].kernel_evidence.sources[0]]){s.current_snapshot_id=id('6');s.current_raw_sha256='f'.repeat(64);}e.captured_inventory_matches_current=false;e.diagnostics=['captured_inventory_changed'];e.captured_inventory_fingerprint=await scopeInvoiceInventoryFingerprint(e.source_inventory);expect((await projectScopeInvoiceKernelEvidence(e)).known_captured_invoice_cost_minor).toBe(540000);});
 it('retains excluded permanent anchors with a partial positive captured subtotal',async()=>{const e=await fixture(),s=e.members[0].kernel_evidence.sources[0];Object.assign(s,{resolved:false,reason:'source_changed',current_snapshot_id:null,current_raw_sha256:null,status:null,amount_minor:null,policy_state:'stale',replaces_estimate_minor:null});Object.assign(e.source_inventory[0],{mapping_state:'excluded',reason:'source_changed',current_snapshot_id:null,current_raw_sha256:null,policy_state:'stale'});e.captured_inventory_matches_current=false;e.diagnostics=['captured_inventory_changed'];e.captured_inventory_fingerprint=await scopeInvoiceInventoryFingerprint(e.source_inventory);const p=await projectScopeInvoiceKernelEvidence(e);expect(p.known_captured_invoice_cost_minor).toBe(270000);expect(p.excluded_source_anchors).toEqual(['0'.repeat(64)]);expect(p.diagnostics).toContain('excluded_scope_source:'+'0'.repeat(64)+':source_changed');});
 it('unknown/empty catalog is null and category/EAC cannot be promoted',async()=>{const e=await fixture();e.members=[];e.source_inventory=[];e.saved_source_references=[];e.captured_inventory_fingerprint=await scopeInvoiceInventoryFingerprint([]);const p=await projectScopeInvoiceKernelEvidence(e);expect(p.known_captured_invoice_cost_minor).toBeNull();expect(p.confirmed_captured_invoice_cost_minor).toBeNull();expect(p.preliminary_captured_invoice_cost_minor).toBeNull();expect(p.eac_minor).toBeNull();expect(p.credit_eligible).toBe(false);await expect(validateScopeInvoiceKernelEvidence({...e,source_coverage:'complete'})).rejects.toThrow();});
 it('rejects duplicate anchors and duplicate local obligation members',async()=>{const e=await fixture();e.source_inventory.push({...e.source_inventory[0]});await expect(validateScopeInvoiceKernelEvidence(e)).rejects.toThrow('duplicate_or_invalid');const f=await fixture();f.members.push({...f.members[0]});await expect(validateScopeInvoiceKernelEvidence(f)).rejects.toThrow('duplicate_or_invalid_scope_member');});
 it('rejects a second member charging an anchor whose sole outer inventory belongs to the first',async()=>{const e=await fixture();e.members[1].kernel_evidence.sources=[structuredClone(e.members[0].kernel_evidence.sources[0])];e.source_inventory.pop();e.saved_source_references.pop();e.captured_inventory_fingerprint=await scopeInvoiceInventoryFingerprint(e.source_inventory);await expect(validateScopeInvoiceKernelEvidence(e)).rejects.toThrow('duplicate_global_child_anchor');});
 it('rejects forged inventory hash/boolean and foreign scope/currency/baseline',async()=>{const e=await fixture();await expect(validateScopeInvoiceKernelEvidence({...e,captured_inventory_fingerprint:'0'.repeat(64)})).rejects.toThrow('hash');await expect(validateScopeInvoiceKernelEvidence({...e,captured_inventory_matches_current:false})).rejects.toThrow('comparison');const f=await fixture();f.members[0].kernel_evidence.organization_id=id('8');await expect(validateScopeInvoiceKernelEvidence(f)).rejects.toThrow('proof_mismatch');await expect(validateScopeInvoiceKernelEvidence({...e,currency:'EUR'})).rejects.toThrow('proof_mismatch');});
 it('rejects calendar-normalized dates, extra caller pricing and unknown numeric types',async()=>{const e=await fixture();await expect(validateScopeInvoiceKernelEvidence({...e,as_of:'2026-02-30T00:00:00Z'})).rejects.toThrow();await expect(validateScopeInvoiceKernelEvidence({...e,amount_minor:0})).rejects.toThrow();await expect(validateScopeInvoiceKernelEvidence({...e,scope_revision:'1'})).rejects.toThrow();});
});
