-- Isolated durable-transport contract fixture; source cost generated by actual native Ops helper.
-- Receipt shapes below test SQL guards only; they are not proof of Finance HTTP delivery.
begin;
insert into public.projects(id,organization_id,deleted_at) values('00000000-0000-4000-8000-000000000007','00000000-0000-4000-8000-000000000001',null);
set local role service_role;
do $$declare p jsonb:=current_setting('test.catering_finance_body')::jsonb;s jsonb;begin
 s:=p->'snapshot';
 insert into public.operations_catering_publish_gates values((s->>'organization_id')::uuid,true);
 insert into public.operations_catering_source_bindings values((s->>'organization_id')::uuid,(s->>'worker_id')::uuid,(s->>'source_organization_id')::uuid,(s->>'source_person_id')::uuid,'https://catering.example/api/project-economy-read','catering-key-1',true);
 insert into public.operations_catering_project_mappings(id,organization_id,worker_id,catering_organization_id,catering_person_id,time_entry_id,workplace_id,work_date,time_zone,project_id,obligation_id,currency,mapping_revision,enabled)
 values((p->>'source_mapping_id')::uuid,(s->>'organization_id')::uuid,(s->>'worker_id')::uuid,(s->>'source_organization_id')::uuid,(s->>'source_person_id')::uuid,
 (s->>'source_time_entry_id')::uuid,'00000000-0000-4000-8000-000000000006',(s->>'work_date')::date,s->>'time_zone',(s->>'project_id')::uuid,(s->>'obligation_id')::uuid,s->>'currency',s->>'mapping_revision',true);
 insert into public.operations_personnel_rate_history(organization_id,worker_id,rate_revision,category,currency,hourly_rate_minor,effective_from,effective_to,source_reference)
 values((s->>'organization_id')::uuid,(s->>'worker_id')::uuid,s->>'rate_revision','work',s->>'currency',(s->>'hourly_rate_minor')::bigint,'2026-09-01','2026-10-01','isolated-native-helper-fixture');
 perform public.publish_operations_catering_cost_v1(s,p->>'raw_entry',null,(p->>'source_mapping_id')::uuid,p->>'source_request_hash',0,'isolated-native-finance-publication');
 insert into operations_catering_private.finance_delivery_gates values((s->>'organization_id')::uuid,false);
 insert into operations_catering_private.finance_delivery_routes values((p->>'route_id')::uuid,(s->>'organization_id')::uuid,(p->>'destination_organization_id')::uuid,p->>'route_revision',p->>'key_id','https://finance.example/functions/v1/operations-catering-cost-receive',true);
 insert into operations_catering_private.finance_delivery_maps values('00000000-0000-4000-8000-000000000025',(s->>'organization_id')::uuid,(s->>'project_id')::uuid,(s->>'obligation_id')::uuid,(p->>'destination_organization_id')::uuid,'00000000-0000-4000-8000-000000000026','destination-v1','SEK',true);
end;$$;
do $$declare p jsonb:=current_setting('test.catering_finance_body')::jsonb;oid uuid;delivery uuid;r jsonb;c jsonb;receipt jsonb;begin
 select id into oid from public.operations_catering_cost_outbox;
 begin perform public.prepare_operations_catering_finance_delivery_v1(oid,(p->>'route_id')::uuid);raise exception 'default-off delivery prepared';exception when insufficient_privilege then null;end;
 begin update operations_catering_private.finance_delivery_gates set organization_id='00000000-0000-4000-8000-000000000099';raise exception 'service rewrote native delivery gate tenant';exception when object_not_in_prerequisite_state then null;end;
 update operations_catering_private.finance_delivery_gates set enabled=true;
 r:=public.prepare_operations_catering_finance_delivery_v1(oid,(p->>'route_id')::uuid);delivery:=(r->>'delivery_id')::uuid;
 if r->>'outcome'<>'prepared' then raise exception 'native durable capture failed';end if;
 r:=public.prepare_operations_catering_finance_delivery_v1(oid,(p->>'route_id')::uuid);
 if r->>'outcome'<>'replayed' or (r->>'delivery_id')::uuid<>delivery then raise exception 'native capture duplicated/rebound';end if;
 c:=public.claim_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-001');
 if c is null or (c->>'raw_body')::jsonb->'snapshot' is distinct from p->'snapshot'
 or c->>'body_sha256'<>encode(sha256(convert_to(c->>'raw_body','UTF8')),'hex') then raise exception 'native capture source/hash changed';end if;
 if public.claim_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-002') is not null then raise exception 'native concurrent lease stolen';end if;
 receipt:=jsonb_build_object('schema','operations-catering-receipt.v1','outcome','accepted','source_organization_id',p->>'operations_organization_id','source_stream_id',p->>'source_stream_id',
 'requested_source_revision',1,'applied_source_revision',1,'current_source_revision',1,'request_body_sha256',c->>'body_sha256','snapshot_receipt_id','00000000-0000-4000-8000-000000000041',
 'snapshot_fingerprint',c->>'body_sha256','receipt_id','00000000-0000-4000-8000-000000000042','destination_organization_id',p->>'destination_organization_id','shadow_only',true);
 begin perform public.finish_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-001',(c->>'lease_token')::uuid,'delivered',receipt||'{"outcome":null}',null);
 raise exception 'null receipt outcome accepted';exception when invalid_parameter_value then null;end;
 begin perform public.finish_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-001',(c->>'lease_token')::uuid,'delivered',receipt||jsonb_build_object('snapshot_fingerprint',repeat('0',64)),null);
 raise exception 'unbound receipt acknowledged';exception when invalid_parameter_value then null;end;
 begin perform public.finish_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-002',(c->>'lease_token')::uuid,'delivered',receipt,null);
 raise exception 'foreign lease finished';exception when insufficient_privilege then null;end;
 r:=public.finish_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-001',(c->>'lease_token')::uuid,'delivered',receipt,null);
 if r->>'status'<>'delivered' or r->>'source_outbox_status'<>'parked' then raise exception 'delivery altered original parked outbox';end if;
 if exists(select 1 from public.operations_catering_cost_outbox where status<>'parked') then raise exception 'legacy parked outbox activated';end if;
 -- The normalized capture-mismatch enum can finish a lease as blocked, not leave it stranded.
 -- A fresh genuine-schema pending version also exercises same-pair destination rotation denial.
 p:=jsonb_set(p,'{snapshot,publication_revision}','2');p:=jsonb_set(p,'{snapshot,source_time_entry_version}','2');
 p:=jsonb_set(p,'{raw_entry}',to_jsonb(jsonb_set((p->>'raw_entry')::jsonb,'{version}','2')::text));
 p:=jsonb_set(p,'{snapshot,source_fingerprint}',to_jsonb(encode(sha256(convert_to(operations_catering_private.canonical_source_json_v1((p->>'raw_entry')::jsonb),'UTF8')),'hex')));
 perform public.publish_operations_catering_cost_v1(p->'snapshot',p->>'raw_entry',null,(p->>'source_mapping_id')::uuid,p->>'source_request_hash',1,'isolated-native-finance-correction');
 select id into oid from public.operations_catering_cost_outbox where source_revision=2;
 update operations_catering_private.finance_delivery_maps set enabled=false;
 insert into operations_catering_private.finance_delivery_maps values('00000000-0000-4000-8000-000000000028',(p->>'operations_organization_id')::uuid,
 '00000000-0000-4000-8000-000000000007','00000000-0000-4000-8000-000000000008',(p->>'destination_organization_id')::uuid,'00000000-0000-4000-8000-000000000027','destination-v2','SEK',true);
 begin perform public.prepare_operations_catering_finance_delivery_v1(oid,(p->>'route_id')::uuid);raise exception 'same pair silently rebound Finance destination';exception when insufficient_privilege then null;end;
 if exists(select 1 from operations_catering_private.finance_delivery_queue where source_outbox_id=oid) then raise exception 'blocked destination rotation captured queue';end if;
 update operations_catering_private.finance_delivery_maps set enabled=false where mapping_id='00000000-0000-4000-8000-000000000028';
 update operations_catering_private.finance_delivery_maps set enabled=true where mapping_id='00000000-0000-4000-8000-000000000025';
 r:=public.prepare_operations_catering_finance_delivery_v1(oid,(p->>'route_id')::uuid);delivery:=(r->>'delivery_id')::uuid;
 c:=public.claim_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-003');
 r:=public.finish_operations_catering_finance_delivery_v1((p->>'operations_organization_id')::uuid,delivery,'fixture-owner-003',(c->>'lease_token')::uuid,'blocked',null,'catering_finance_capture_or_configuration_invalid');
 if r->>'status'<>'blocked' then raise exception 'locked capture-mismatch error left lease stranded';end if;

 begin update operations_catering_private.finance_delivery_queue set raw_body='{}';raise exception 'service mutated capture';exception when insufficient_privilege then null;end;
end;$$;
reset role;
select 'PASS native Catering explicit durable capture/actual native publication bytes/default-off/replay/lease/strict hash receipt/original parked outbox unchanged' as result;
rollback;
