// Isolated SQL fixture generated by the actual native Operations cost helper.
// This is not a provider response or proof of deployed source delivery.
import {
  calculateCateringPersonnelEvidence,
  type CateringTimeEntry,
} from "../../supabase/functions/_shared/catering-project-evidence.ts";
import { rawBodySha256 } from "../../supabase/functions/_shared/project-personnel-ingestion-transport.ts";
import type { CateringFinanceClaim } from "../../supabase/functions/_shared/catering-finance-transport.ts";
const id = (n: number) =>
  `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const endpoint =
  "https://finance.example/functions/v1/operations-catering-cost-receive";
const config = {
  enabled: true,
  endpoint,
  keyId: "native-finance-key",
  secret: "isolated-only-native-finance-hmac-at-least32",
};
export async function createIsolatedCateringFinanceClaim(): Promise<CateringFinanceClaim> {
  const entry: CateringTimeEntry = {
    id: id(5),
    organization_id: id(3),
    person_id: id(4),
    workplace_id: id(6),
    started_at: "2026-09-30T08:00:00Z",
    ended_at: "2026-09-30T10:00:00Z",
    break_minutes: 15,
    status: "pending",
    approved_by: null,
    approved_at: null,
    version: 1,
    source: "manual",
  };
  // Unit-only source fixture calculated by the actual Operations historical helper.
  const snapshot = await calculateCateringPersonnelEvidence(
    entry,
    null,
    {
      catering_organization_id: id(3),
      catering_person_id: id(4),
      organization_id: id(1),
      worker_id: id(2),
      project_id: id(7),
      obligation_id: id(8),
      mapping_revision: "allocation-v1",
      work_date: "2026-09-30",
      time_zone: "Europe/Stockholm",
      currency: "SEK",
      publication_revision: 1,
      project_review_status: "preliminary",
    },
    [
      {
        organization_id: id(1),
        worker_id: id(2),
        category: "work",
        currency: "SEK",
        rate_revision: "native-september-rate",
        hourly_rate_minor: 30001,
        effective_from: "2026-09-01",
        effective_to: "2026-10-01",
      },
    ],
  );
  const rawEntry = JSON.stringify(entry);
  const body = {
    schema_version: "operations-catering-delivery.v1",
    operations_organization_id: id(1),
    destination_organization_id: id(20),
    route_id: id(21),
    route_revision: "route-v1",
    key_id: config.keyId,
    source_stream_id: `catering:${id(3)}:${id(5)}`,
    source_outbox_id: id(22),
    source_observation_id: id(23),
    source_mapping_id: id(24),
    destinations: [{ project_id: id(7), obligation_id: id(8) }],
    destination_mappings: [
      {
        mapping_id: id(25),
        mapping_revision: "destination-v1",
        source_project_id: id(7),
        source_obligation_id: id(8),
        destination_project_id: id(26),
        currency: "SEK",
      },
    ],
    snapshot,
    raw_entry: rawEntry,
    raw_review: null,
    raw_entry_sha256: await rawBodySha256(rawEntry),
    raw_review_sha256: null,
    source_request_hash: await rawBodySha256(
      JSON.stringify({
        organizationId: id(3),
        personId: id(4),
        timeEntryId: id(5),
        expectedVersion: 1,
      }),
    ),
  };
  const raw = JSON.stringify(body);
  return {
    id: id(30),
    source_outbox_id: body.source_outbox_id,
    organization_id: id(1),
    source_stream_id: body.source_stream_id,
    source_revision: 1,
    raw_body: raw,
    body_sha256: await rawBodySha256(raw),
    destination_organization_id: id(20),
    route_id: id(21),
    route_revision: "route-v1",
    key_id: config.keyId,
    endpoint_url: endpoint,
    lease_owner: "native-fixture-worker",
    lease_token: id(31),
  };
}

if (import.meta.main) {
  if (Deno.env.get("CATERING_PROJECT_ECONOMY_ISOLATED_TEST") !== "true")
    throw new Error("isolated_fixture_required");
  const claim = await createIsolatedCateringFinanceClaim();
  const value = claim.raw_body.replaceAll("'", "''");
  console.log(
    "select set_config('test.catering_finance_body','" + value + "',false);",
  );
}
