\set ON_ERROR_STOP on
-- Exact immutable authority fixture produced by operations-obligation-fixture.ts.
-- All source evidence arrives through actual service receiver RPCs; transaction rolls back.
begin;
create temporary table capacity_fixture(data jsonb not null);
insert into capacity_fixture values(:'fixture'::jsonb);
grant select on capacity_fixture to authenticated,service_role;
create function pg_temp.capacity_assert(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'credit capacity assertion failed: %',label;end if;end;$$;
create function pg_temp.capacity_fail_event() returns trigger language plpgsql as $$begin raise exception 'synthetic capacity atomic failure' using errcode='22023';end;$$;
insert into public.operations_finance_invoice_enrollments values('fixture_own_credit_v1','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_invoice_project_scopes values('fixture_own_credit_v1','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true);
insert into public.operations_finance_credit_v2_enrollments values('fixture_own_credit_v2','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_credit_v2_project_scopes values('fixture_own_credit_v2','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true);
set local role service_role;
do $$declare f jsonb;r jsonb;begin select data into f from capacity_fixture;
 r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_own_credit_v1',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_own_credit_original',f->>'rawInvoice');
 perform pg_temp.capacity_assert(r->>'outcome'='accepted','real original receiver');end;$$;
reset role;
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
do $$declare f jsonb;p jsonb;credit jsonb;command jsonb;bind jsonb;r jsonb;first jsonb;orig_snapshot uuid;credit_snapshot uuid;binding uuid;anchor text;original_anchor text;
 org uuid:='11111111-1111-4111-8111-111111111111';project uuid:='55555555-5555-4555-8555-555555555555';obligation uuid:='abababab-abab-4aba-8aba-abababababab';begin
 select data into f from capacity_fixture;select id into orig_snapshot from public.operations_finance_invoice_snapshots where source_revision=1;
 original_anchor:=f->>'anchor';
 credit:=f->'invoice'||jsonb_build_object('schema_version','finance-project-invoice-destination-v2','invoice_id','89898989-8989-4898-8989-898989898989','invoice_kind','credit','document_fingerprint',repeat('c',64),
 'recipient_net_minor',-50000,'source_revision',1,'source_economic_revision',1,'source_economic_publication_fingerprint',repeat('d',64),'source_publication_fingerprint',repeat('e',64),'credit_relation_coverage','linked','credit_relationship_fingerprint',repeat('f',64));
 anchor:=operations_economy_private.invoice_source_anchor_v1('99999999-9999-4999-8999-999999999999','89898989-8989-4898-8989-898989898989',(f#>>'{invoice,allocations,0,allocation_id}')::uuid,repeat('c',64),'SEK');
 credit:=credit||jsonb_build_object('allocations',jsonb_build_array((f#>'{invoice,allocations,0}')||jsonb_build_object('amount_minor',-50000,'source_anchor',anchor,'credited_source_anchor',original_anchor)));
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_own_credit_v2_first',replace(credit::text,': ',':'));execute 'reset role';credit_snapshot:=(r->>'snapshot_receipt_id')::uuid;
 execute 'set local role authenticated';perform public.append_operations_manual_obligation_baseline_v1(f->'baseline');
 bind:=jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',orig_snapshot,'source_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_economic_revision',1,'expected_economic_fingerprint',repeat('a',64),'idempotency_key','synthetic-own-credit-original-bind','reason','Genuine positive original ownership');
 r:=public.bind_operations_invoice_obligation_v1(bind);binding:=(r->>'event_id')::uuid;
 command:=jsonb_build_object('schema_version','operations-obligation-credit-assign.v1','project_id',project,'obligation_id',obligation,'expected_baseline_revision',1,'credit_snapshot_id',credit_snapshot,'credit_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_credit_economic_revision',1,'expected_credit_economic_fingerprint',repeat('d',64),'expected_original_binding_event_id',binding,'expected_assignment_revision',0,'idempotency_key','synthetic-own-credit-assignment','reason','Assign actual own credit to same original obligation');
 first:=public.assign_operations_obligation_own_credit_v1(command);execute 'reset role';
 command:=jsonb_build_object('schema_version','operations-obligation-credit-capacity.v1','project_id',project,'obligation_id',obligation,'assignment_event_id',first->'event_id','expected_capacity_revision',0,'idempotency_key','synthetic-credit-capacity-first','reason','Copy actual source-bound local credit capacity');
 execute 'set local role authenticated';begin perform public.append_operations_obligation_credit_capacity_v1(command);raise exception 'default-off capacity accepted';exception when insufficient_privilege then if sqlerrm<>'credit_capacity_gate_disabled' then raise;end if;end;execute 'reset role';
 insert into public.operations_obligation_credit_capacity_gates(organization_id) values(org);perform pg_temp.capacity_assert((select not enabled from public.operations_obligation_credit_capacity_gates),'gate defaults false');update public.operations_obligation_credit_capacity_gates set enabled=true;
 execute 'set local role authenticated';
 for p in select value from jsonb_array_elements(jsonb_build_array(command||'{"reserved_minor":1}',command||'{"credit_eligible":true}',command||'{"expected_capacity_revision":"0"}',command||'{"assignment_event_id":["aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa"]}')) loop begin perform public.append_operations_obligation_credit_capacity_v1(p);raise exception 'invalid capacity command accepted';exception when sqlstate '22023' then null;end;end loop;
 r:=public.append_operations_obligation_credit_capacity_v1(command||'{"expected_capacity_revision":1}');perform pg_temp.capacity_assert(r->>'outcome'='stale' and r->>'current_revision'='0','stale capacity no ghost');execute 'reset role';perform pg_temp.capacity_assert(not exists(select 1 from public.operations_obligation_credit_capacity_heads),'stale no capacity head');
 execute 'create trigger synthetic_capacity_rollback before insert on public.operations_obligation_credit_capacity_events for each row execute function pg_temp.capacity_fail_event()';execute 'set local role authenticated';begin perform public.append_operations_obligation_credit_capacity_v1(command);raise exception 'capacity failure did not rollback';exception when sqlstate '22023' then if sqlerrm<>'synthetic capacity atomic failure' then raise;end if;end;execute 'reset role';perform pg_temp.capacity_assert(not exists(select 1 from public.operations_obligation_credit_capacity_heads),'event failure rolls back head');execute 'drop trigger synthetic_capacity_rollback on public.operations_obligation_credit_capacity_events';execute 'set local role authenticated';
 first:=public.append_operations_obligation_credit_capacity_v1(command);perform pg_temp.capacity_assert(first->>'outcome'='accepted' and first->>'reserved_minor'='50000' and first->>'credit_eligible'='false' and first->'eac_minor'='null','actual absolute saved credit copied, no EAC');
 r:=public.append_operations_obligation_credit_capacity_v1(command);perform pg_temp.capacity_assert(r->>'outcome'='replayed' and r->>'receipt_currentness'='historical_provenance_only','replay is provenance only');
 begin perform public.append_operations_obligation_credit_capacity_v1(command||'{"reason":"Changed capacity explanation"}');raise exception 'idempotency conflict accepted';exception when unique_violation then if sqlerrm<>'credit_capacity_idempotency_conflict' then raise;end if;end;execute 'reset role';
 execute 'set local role service_role';r:=public.read_operations_obligation_credit_capacity_v1(org,project,obligation,anchor);perform pg_temp.capacity_assert(r->>'state'='local_capacity_proven' and r->>'original_amount_minor'='540000' and r->>'retained_aggregate_minor'='50000' and r->>'credit_eligible'='false','local original capacity only');execute 'reset role';
 -- A second genuine saved credit cannot exceed the same original's retained total.
 p:=credit||jsonb_build_object('invoice_id','78787878-7878-4787-8787-787878787878','recipient_net_minor',-500000);
 original_anchor:=anchor; -- retain first own anchor selector separately
 anchor:=operations_economy_private.invoice_source_anchor_v1('99999999-9999-4999-8999-999999999999','78787878-7878-4787-8787-787878787878',(f#>>'{invoice,allocations,0,allocation_id}')::uuid,repeat('c',64),'SEK');
 p:=jsonb_set(p,'{allocations,0}',(credit#>'{allocations,0}')||jsonb_build_object('amount_minor',-500000,'source_anchor',anchor));
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_capacity_second_credit',p::text);execute 'reset role';credit_snapshot:=(r->>'snapshot_receipt_id')::uuid;
 bind:=jsonb_build_object('schema_version','operations-obligation-credit-assign.v1','project_id',project,'obligation_id',obligation,'expected_baseline_revision',1,'credit_snapshot_id',credit_snapshot,'credit_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_credit_economic_revision',1,'expected_credit_economic_fingerprint',repeat('d',64),'expected_original_binding_event_id',binding,'expected_assignment_revision',0,'idempotency_key','synthetic-capacity-second-assignment','reason','Own second actual negative credit');
 execute 'set local role authenticated';r:=public.assign_operations_obligation_own_credit_v1(bind);
 bind:=jsonb_build_object('schema_version','operations-obligation-credit-capacity.v1','project_id',project,'obligation_id',obligation,'assignment_event_id',r->'event_id','expected_capacity_revision',0,'idempotency_key','synthetic-capacity-second-reserve','reason','Reserve actual second credit');
 begin perform public.append_operations_obligation_credit_capacity_v1(bind);raise exception 'original capacity exceeded';exception when sqlstate '22023' then if sqlerrm<>'actual_original_credit_capacity_exceeded' then raise;end if;end;execute 'reset role';
 -- Rejection of first source invalidates its proof but must retain its reservation.
 credit:=jsonb_set(credit||jsonb_build_object('source_revision',2,'source_economic_revision',2,'source_economic_publication_fingerprint',repeat('9',64),'source_publication_fingerprint',repeat('8',64),'invoice_status','rejected'),'{allocations,0,status}','"rejected"');
 execute 'set local role service_role';perform public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_capacity_first_rejected',credit::text);r:=public.read_operations_obligation_credit_capacity_v1(org,project,obligation,original_anchor);perform pg_temp.capacity_assert(r->>'state'='unresolved','rejected source capacity unresolved');execute 'reset role';execute 'set local role authenticated';
 begin perform public.append_operations_obligation_credit_capacity_v1(bind);raise exception 'stale rejected reserve auto released';exception when sqlstate '22023' then if sqlerrm<>'actual_original_credit_capacity_exceeded' then raise;end if;end;
 r:=public.append_operations_obligation_credit_capacity_v1(command);perform pg_temp.capacity_assert(r->>'receipt_currentness'='historical_provenance_only','stale-source retry remains historical');execute 'reset role';
 -- Correct second actual source to490000, then explicit new assignment: retained50000+490000 fits exactly.
 p:=jsonb_set(p||jsonb_build_object('source_revision',2,'source_economic_revision',2,'source_economic_publication_fingerprint',repeat('7',64),'source_publication_fingerprint',repeat('6',64),'recipient_net_minor',-490000),'{allocations,0,amount_minor}','-490000');
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_capacity_second_corrected',p::text);execute 'reset role';credit_snapshot:=(r->>'snapshot_receipt_id')::uuid;
 bind:=jsonb_build_object('schema_version','operations-obligation-credit-assign.v1','project_id',project,'obligation_id',obligation,'expected_baseline_revision',1,'credit_snapshot_id',credit_snapshot,'credit_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_credit_economic_revision',2,'expected_credit_economic_fingerprint',repeat('7',64),'expected_original_binding_event_id',binding,'expected_assignment_revision',1,'idempotency_key','synthetic-capacity-second-correction','reason','Adopt corrected actual credit amount');execute 'set local role authenticated';r:=public.assign_operations_obligation_own_credit_v1(bind);
 bind:=jsonb_build_object('schema_version','operations-obligation-credit-capacity.v1','project_id',project,'obligation_id',obligation,'assignment_event_id',r->'event_id','expected_capacity_revision',0,'idempotency_key','synthetic-capacity-second-corrected','reason','Explicit current actual source reservation');
 r:=public.append_operations_obligation_credit_capacity_v1(bind);perform pg_temp.capacity_assert(r->>'outcome'='accepted' and r->>'reserved_minor'='490000' and r->>'retained_aggregate_minor'='540000','stale first reservation retained at exact original bound');execute 'reset role';
 execute 'set local role service_role';r:=public.read_operations_obligation_credit_capacity_v1(org,project,obligation,anchor);perform pg_temp.capacity_assert(r->>'state'='local_capacity_proven' and r->>'credit_eligible'='false','current second reservation locally proven only');execute 'reset role';
 -- A lower genuine original invalidates proof; explicit revalidation cannot overreserve it.
 p:=jsonb_set(f->'invoice'||jsonb_build_object('source_revision',2,'source_publication_fingerprint',repeat('5',64),'recipient_net_minor',400000),'{allocations,0,amount_minor}','400000');
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_own_credit_v1',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_capacity_original_lower',p::text);orig_snapshot:=(r->>'snapshot_receipt_id')::uuid;
 r:=public.read_operations_obligation_credit_capacity_v1(org,project,obligation,anchor);perform pg_temp.capacity_assert(r->>'state'='unresolved','lower original invalidates saved capacity');execute 'reset role';
 execute 'set local role authenticated';r:=public.bind_operations_invoice_obligation_v1(jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',orig_snapshot,'source_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_economic_revision',2,'expected_economic_fingerprint',repeat('5',64),'idempotency_key','synthetic-capacity-original-rebound','reason','Adopt actual lower original economics'));binding:=(r->>'event_id')::uuid;
 r:=public.assign_operations_obligation_own_credit_v1(jsonb_build_object('schema_version','operations-obligation-credit-assign.v1','project_id',project,'obligation_id',obligation,'expected_baseline_revision',1,'credit_snapshot_id',credit_snapshot,'credit_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_credit_economic_revision',2,'expected_credit_economic_fingerprint',repeat('7',64),'expected_original_binding_event_id',binding,'expected_assignment_revision',2,'idempotency_key','synthetic-capacity-lower-original-assignment','reason','Explicit current source and lower original proof'));
 bind:=bind||jsonb_build_object('assignment_event_id',r->'event_id','expected_capacity_revision',1,'idempotency_key','synthetic-capacity-lower-original-reserve');
 begin perform public.append_operations_obligation_credit_capacity_v1(bind);raise exception 'lower original overreservation accepted';exception when sqlstate '22023' then if sqlerrm<>'actual_original_credit_capacity_exceeded' then raise;end if;end;execute 'reset role';
 -- A different actual original cannot silently transfer the fixed reservation.
 begin
 p:=f->'invoice'||jsonb_build_object('invoice_id','45454545-4545-4454-8454-454545454545');execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_own_credit_v1',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_capacity_other_original',p::text);execute 'reset role';orig_snapshot:=(r->>'snapshot_receipt_id')::uuid;
 original_anchor:=operations_economy_private.invoice_source_anchor_v1('99999999-9999-4999-8999-999999999999','45454545-4545-4454-8454-454545454545',(f#>>'{invoice,allocations,0,allocation_id}')::uuid,f#>>'{invoice,document_fingerprint}','SEK');
 execute 'set local role authenticated';r:=public.bind_operations_invoice_obligation_v1(jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',orig_snapshot,'source_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_economic_revision',1,'expected_economic_fingerprint',repeat('a',64),'idempotency_key','synthetic-capacity-other-original-bind','reason','Actual second original ownership'));binding:=(r->>'event_id')::uuid;execute 'reset role';
 select envelope into p from public.operations_finance_credit_v2_snapshots where id=credit_snapshot;
 p:=jsonb_set(p||jsonb_build_object('source_revision',3,'source_publication_fingerprint',repeat('4',64),'credit_relationship_fingerprint',repeat('3',64)),'{allocations,0,credited_source_anchor}',to_jsonb(original_anchor));
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_capacity_relationship_move',p::text);execute 'reset role';
 execute 'set local role authenticated';r:=public.assign_operations_obligation_own_credit_v1(jsonb_build_object('schema_version','operations-obligation-credit-assign.v1','project_id',project,'obligation_id',obligation,'expected_baseline_revision',1,'credit_snapshot_id',r->'snapshot_receipt_id','credit_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_credit_economic_revision',2,'expected_credit_economic_fingerprint',repeat('7',64),'expected_original_binding_event_id',binding,'expected_assignment_revision',3,'idempotency_key','synthetic-capacity-move-assignment','reason','Capture actual relationship change without releasing reservation'));
 begin perform public.append_operations_obligation_credit_capacity_v1(bind||jsonb_build_object('assignment_event_id',r->'event_id','idempotency_key','synthetic-capacity-move-reservation'));raise exception 'reservation moved to other original';exception when unique_violation then if sqlerrm<>'credit_capacity_permanent_original_conflict' then raise;end if;end;execute 'reset role';
 raise exception 'synthetic rollback capacity transfer attempt' using errcode='22023';exception when sqlstate '22023' then if sqlerrm<>'synthetic rollback capacity transfer attempt' then raise;end if;end;
 update public.operations_obligation_credit_capacity_gates set enabled=false;execute 'set local role service_role';r:=public.read_operations_obligation_credit_capacity_v1(org,project,obligation,anchor);perform pg_temp.capacity_assert(r->>'state'='unresolved' and r->>'reason'='gate_disabled','revocation blocks current proof');execute 'reset role';update public.operations_obligation_credit_capacity_gates set enabled=true;
 perform pg_temp.capacity_assert((select sum(e.reserved_minor)=540000 from public.operations_obligation_credit_capacity_heads h join public.operations_obligation_credit_capacity_events e on e.organization_id=h.organization_id and e.source_anchor=h.source_anchor and e.revision=h.current_revision),'gate/status never release actual reservations');
 begin update public.operations_obligation_credit_capacity_events set reason='rewrite';raise exception 'capacity event rewrite accepted';exception when sqlstate '55000' then null;end;
 begin delete from public.operations_obligation_credit_capacity_heads;raise exception 'capacity head delete accepted';exception when sqlstate '55000' then null;end;
 begin truncate public.operations_obligation_credit_capacity_events cascade;raise exception 'capacity truncate accepted';exception when sqlstate '55000' then null;end;
end;$$;
rollback;
select 'operations-obligation-credit-capacity-postgres PASS' as result;
