\set ON_ERROR_STOP on
-- Disposable foundation schema only; all fixture mutations roll back.
begin;
create temporary table scope_invoice_input(data jsonb not null);insert into scope_invoice_input values(:'fixture'::jsonb);grant select on scope_invoice_input to authenticated,service_role;
create temporary table scope_invoice_vectors(label text primary key,evidence jsonb not null);
create function pg_temp.scope_invoice_assert(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'scope invoice assertion failed: %',label;end if;end;$$;
insert into public.bookings values('Separate-Order-99','11111111-1111-4111-8111-111111111111',null);
update public.projects set booking_id='Separate-Order-99' where id='77777777-7777-4777-8777-777777777777';
insert into public.large_project_bookings values('14141414-1414-4414-8414-141414141414','11111111-1111-4111-8111-111111111111','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Separate-Order-99');
insert into public.operations_finance_invoice_enrollments values('fixture_scope_kernel','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_invoice_project_scopes values('fixture_scope_kernel','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true),('fixture_scope_kernel','67676767-6767-4676-8676-676767676767','77777777-7777-4777-8777-777777777777',true);
insert into public.operations_finance_credit_v2_enrollments values('fixture_scope_kernel_v2','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_credit_v2_project_scopes values('fixture_scope_kernel_v2','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true),('fixture_scope_kernel_v2','67676767-6767-4676-8676-676767676767','77777777-7777-4777-8777-777777777777',true);
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
do $$declare f jsonb;body jsonb;r jsonb;preview jsonb;scope_command jsonb;compose jsonb;request jsonb;policies jsonb:='[]';policy jsonb;baseline_ids jsonb:='[]';refs jsonb;baseline uuid;binding uuid;snapshot uuid;allocation jsonb;project uuid;obligation uuid;v2 jsonb;source_anchor text;i int;capture jsonb;empty_request jsonb;begin
 select data into f from scope_invoice_input;
 body:=f->'invoice'||jsonb_build_object('allocations',jsonb_build_array(jsonb_set(f#>'{invoice,allocations,0}','{amount_minor}','270000'),(f#>'{invoice,allocations,0}')||jsonb_build_object('allocation_id','71717171-7171-4717-8717-717171717171','project_id','67676767-6767-4676-8676-676767676767','destination_project_id','77777777-7777-4777-8777-777777777777','cost_line_id','80808080-8080-4808-8808-808080808080','amount_minor',270000)));
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_scope_kernel',floor(extract(epoch from clock_timestamp()))::bigint::text,'native_scope_kernel_split',body::text);execute 'reset role';snapshot:=(r->>'snapshot_receipt_id')::uuid;
 execute 'set local role authenticated';preview:=public.preview_operations_project_scope_v1('large_project','cccccccc-cccc-4ccc-8ccc-cccccccccccc');perform pg_temp.scope_invoice_assert(jsonb_array_length(preview#>'{membership,local_booking_ids}')=2 and jsonb_array_length(preview#>'{membership,source_project_ids}')=2,'two independent real bookings and leaves');
 scope_command:=jsonb_build_object('schema','operations-project-scope-enroll.v1','economic_scope_id','90909090-9090-4909-8909-909090909090','root_kind','large_project','root_id','cccccccc-cccc-4ccc-8ccc-cccccccccccc','expected_revision',0,'expected_membership_fingerprint',preview->>'membership_fingerprint','idempotency_key','native-scope-kernel-enroll','reason','Explicit two-booking canonical owner');perform public.enroll_operations_project_scope_v1(scope_command);
 for allocation in select value from jsonb_array_elements(body->'allocations') loop
 project:=(allocation->>'destination_project_id')::uuid;obligation:=case when project='55555555-5555-4555-8555-555555555555' then 'abababab-abab-4aba-8aba-abababababab'::uuid else 'cdcdcdcd-cdcd-4cdc-8cdc-cdcdcdcdcdcd'::uuid end;
 r:=public.append_operations_manual_obligation_baseline_v1(f->'baseline'||jsonb_build_object('project_id',project,'obligation_id',obligation,'estimate_minor',case when project='55555555-5555-4555-8555-555555555555' then 1000000 else 500000 end,'committed_minor',case when project='55555555-5555-4555-8555-555555555555' then null else 200000 end,'idempotency_key','native-scope-kernel-baseline-'||project));baseline:=(r->>'event_id')::uuid;baseline_ids:=baseline_ids||jsonb_build_array(baseline);
 r:=public.bind_operations_invoice_obligation_v1(jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',snapshot,'source_allocation_id',allocation->'allocation_id','expected_economic_revision',1,'expected_economic_fingerprint',repeat('a',64),'idempotency_key','native-scope-kernel-bind-'||project,'reason','Own exact split allocation once'));binding:=(r->>'event_id')::uuid;
 policy:=jsonb_build_object('schema_version','operations-obligation-source-policy.v1','project_id',project,'obligation_id',obligation,'baseline_event_id',baseline,'binding_event_id',binding,'expected_policy_revision',0,'replaces_estimate_minor',300000,'consumes_commitment_minor',case when project='55555555-5555-4555-8555-555555555555' then null else 100000 end,'idempotency_key','native-scope-kernel-policy-'||project,'reason','Explicit planned variance and nullable policy');perform public.append_operations_obligation_source_policy_v1(policy);policies:=policies||jsonb_build_array(policy);
 end loop;
 r:=public.append_operations_manual_obligation_baseline_v1(f->'baseline'||jsonb_build_object('obligation_id','efefefef-efef-4efe-8efe-efefefefefef','category','personnel','cost_basis','time','idempotency_key','native-scope-kernel-unsupported'));baseline_ids:=baseline_ids||jsonb_build_array(r->'event_id');
 compose:=jsonb_build_object('schema_version','operations-scope-obligation-compose.v1','economic_scope_id',scope_command->'economic_scope_id','expected_scope_revision',1,'expected_membership_fingerprint',preview->'membership_fingerprint','expected_composition_revision',0,'currency','SEK','baseline_event_ids',baseline_ids,'idempotency_key','native-scope-kernel-compose','reason','Selected current local manual obligations, no whole budget');r:=public.compose_operations_scope_obligations_v1(compose);execute 'reset role';
 request:=jsonb_build_object('schema_version','operations-scope-invoice-kernel-read.v1','organization_id','11111111-1111-4111-8111-111111111111','economic_scope_id',scope_command->'economic_scope_id','expected_scope_revision',1,'expected_membership_fingerprint',preview->'membership_fingerprint','expected_composition_revision',1,'expected_composition_fingerprint',r->'fingerprint');
 execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request);raise exception 'disabled scope read accepted';exception when insufficient_privilege then if sqlerrm<>'scope_invoice_read_gate_disabled' then raise;end if;end;execute 'reset role';
 insert into public.operations_scope_invoice_kernel_read_gates values('11111111-1111-4111-8111-111111111111',true);insert into public.operations_invoice_obligation_kernel_read_gates values('11111111-1111-4111-8111-111111111111',true);
 execute 'set local role service_role';capture:=public.read_operations_scope_invoice_kernel_evidence_v1(request);execute 'reset role';perform pg_temp.scope_invoice_assert(jsonb_array_length(capture->'members')=3 and jsonb_array_length(capture->'source_inventory')=2 and capture->'captured_inventory_matches_current'='true','split allocations and unknown noninvoice member captured once');insert into scope_invoice_vectors values('split_initial',capture);
 select document->'source_inventory' into refs from public.operations_scope_obligation_compositions where composition_revision=1;
 execute 'set local role authenticated';perform public.append_operations_obligation_source_policy_v1(policies->0||jsonb_build_object('expected_policy_revision',1,'replaces_estimate_minor',350000,'idempotency_key','native-scope-kernel-new-policy'));execute 'reset role';
 execute 'set local role service_role';capture:=public.read_operations_scope_invoice_kernel_evidence_v1(request);execute 'reset role';perform pg_temp.scope_invoice_assert(capture->'captured_inventory_matches_current'='false' and capture->'diagnostics' ? 'captured_inventory_changed' and capture->'eac_minor'='null' and refs=(select document->'source_inventory' from public.operations_scope_obligation_compositions where composition_revision=1),'fresh policy does not rewrite old inventory or coverage');insert into scope_invoice_vectors values('new_policy',capture);
 -- Actual coequal V2 enrichment retains valid split money but changes current proof refs.
 v2:=body||jsonb_build_object('schema_version','finance-project-invoice-destination-v2','source_economic_revision',1,'source_economic_publication_fingerprint',repeat('a',64),'source_publication_fingerprint',repeat('c',64),'credit_relationship_fingerprint',null);
 allocation:='[]';for r in select value from jsonb_array_elements(body->'allocations') loop source_anchor:=operations_economy_private.invoice_source_anchor_v1((body->>'source_organization_id')::uuid,(body->>'invoice_id')::uuid,(r->>'allocation_id')::uuid,body->>'document_fingerprint',body->>'currency');allocation:=allocation||jsonb_build_array(r||jsonb_build_object('source_anchor',source_anchor,'credited_source_anchor',null));end loop;v2:=v2||jsonb_build_object('allocations',allocation);
 execute 'set local role service_role';perform public.operations_receive_finance_project_invoice_destination_v2('fixture_scope_kernel_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'native_scope_kernel_coequal',v2::text);capture:=public.read_operations_scope_invoice_kernel_evidence_v1(request);execute 'reset role';insert into scope_invoice_vectors values('coequal_v2',capture);
 -- Strict direct-RPC failures do not silently degrade to current partial data.
 execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request||'{"amount_minor":0}');raise exception 'caller amount accepted';exception when sqlstate '22023' then if sqlerrm<>'exact_scope_invoice_request_required' then raise;end if;end;
 begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request||'{"expected_scope_revision":"1"}');raise exception 'string revision accepted';exception when sqlstate '22023' then if sqlerrm<>'invalid_scope_invoice_revision' then raise;end if;end;
 begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request||'{"expected_composition_revision":2}');raise exception 'wrong composition accepted';exception when sqlstate '22023' then if sqlerrm<>'current_scope_invoice_composition_required' then raise;end if;end;execute 'reset role';
 execute 'set local role authenticated';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request);raise exception 'authenticated direct service read allowed';exception when insufficient_privilege then null;end;execute 'reset role';
 -- Same endpoints with a new relationship ID is a new graph, not same membership.
 begin
 delete from public.large_project_bookings where id='14141414-1414-4414-8414-141414141414';insert into public.large_project_bookings values('15151515-1515-4515-8515-151515151515','11111111-1111-4111-8111-111111111111','cccccccc-cccc-4ccc-8ccc-cccccccccccc','Separate-Order-99');
 execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request);raise exception 'changed graph accepted';exception when sqlstate '22023' then if sqlerrm<>'current_scope_invoice_graph_required' then raise;end if;end;execute 'reset role';raise exception 'restore isolated graph' using errcode='22023';exception when sqlstate '22023' then if sqlerrm<>'restore isolated graph' then raise;end if;end;
 begin
 update public.large_projects set organization_id='88888888-8888-4888-8888-888888888888' where id='cccccccc-cccc-4ccc-8ccc-cccccccccccc';execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request);raise exception 'foreign root accepted';exception when insufficient_privilege then if sqlerrm<>'scope_root_missing_or_foreign' then raise;end if;end;execute 'reset role';raise exception 'restore isolated root' using errcode='22023';exception when sqlstate '22023' then if sqlerrm<>'restore isolated root' then raise;end if;end;
 begin
 execute 'set local role authenticated';perform public.append_operations_manual_obligation_baseline_v1(f->'baseline'||jsonb_build_object('expected_revision',1,'estimate_minor',1100000,'idempotency_key','native-scope-kernel-changed-baseline'));execute 'reset role';execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request);raise exception 'old baseline accepted';exception when sqlstate '22023' then if sqlerrm<>'current_scope_invoice_baseline_required' then raise;end if;end;execute 'reset role';raise exception 'restore isolated baseline' using errcode='22023';exception when sqlstate '22023' then if sqlerrm<>'restore isolated baseline' then raise;end if;end;
 -- Global cap is proved through 100 genuine additional source receiver/binding
 -- RPCs spread into the same selected baseline set; no raw ledger injection.
 begin
 for i in 1..100 loop
 r:=body||jsonb_build_object('invoice_id',md5('scope-cap-'||i)::uuid,'recipient_net_minor',1,'source_publication_fingerprint',encode(sha256(convert_to('scope-cap-'||i,'UTF8')),'hex'),'allocations',jsonb_build_array(jsonb_set(body#>'{allocations,0}','{amount_minor}','1')));
 execute 'set local role service_role';capture:=public.operations_receive_finance_project_invoice_destination_v1('fixture_scope_kernel',floor(extract(epoch from clock_timestamp()))::bigint::text,'native_scope_cap_'||i,r::text);execute 'reset role';
 execute 'set local role authenticated';perform public.bind_operations_invoice_obligation_v1(jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id','55555555-5555-4555-8555-555555555555','obligation_id','abababab-abab-4aba-8aba-abababababab','expected_obligation_revision',1,'source_snapshot_id',capture->'snapshot_receipt_id','source_allocation_id',body#>'{allocations,0,allocation_id}','expected_economic_revision',1,'expected_economic_fingerprint',r->'source_publication_fingerprint','idempotency_key','native-scope-global-cap-bind-'||i,'reason','Actual isolated source tests global cap'));execute 'reset role';
 end loop;
 execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(request);raise exception 'global source cap bypassed';exception when sqlstate '22023' then if sqlerrm<>'scope_invoice_global_selector_limit' then raise;end if;end;execute 'reset role';
 raise exception 'restore isolated global cap sources' using errcode='22023';exception when sqlstate '22023' then if sqlerrm<>'restore isolated global cap sources' then raise;end if;end;
 perform pg_temp.scope_invoice_assert((select count(*)=1 from public.operations_finance_invoice_streams) and (select count(*)=2 from public.operations_project_obligation_invoice_bindings),'global cap failure has no retained synthetic sources');
 -- A genuine newer V2 body makes all old positive V1 binding prices unavailable.
 v2:=jsonb_set(jsonb_set(v2||jsonb_build_object('source_revision',2,'source_economic_revision',2,'source_economic_publication_fingerprint',repeat('d',64),'source_publication_fingerprint',repeat('e',64),'recipient_net_minor',450000),'{allocations,0,amount_minor}','200000'),'{allocations,1,amount_minor}','250000');
 execute 'set local role service_role';perform public.operations_receive_finance_project_invoice_destination_v2('fixture_scope_kernel_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'native_scope_kernel_higher',v2::text);capture:=public.read_operations_scope_invoice_kernel_evidence_v1(request);execute 'reset role';perform pg_temp.scope_invoice_assert(jsonb_array_length(capture->'source_inventory')=2 and not exists(select 1 from jsonb_array_elements(capture->'source_inventory')s where s->>'mapping_state'<>'excluded'),'every old anchor retained without old money');insert into scope_invoice_vectors values('higher_v2',capture);
 -- A saved empty baseline selection is explicit unknown, not project cost zero.
 execute 'set local role authenticated';r:=public.compose_operations_scope_obligations_v1(compose||jsonb_build_object('expected_composition_revision',1,'baseline_event_ids','[]'::jsonb,'idempotency_key','native-scope-kernel-empty-selection'));execute 'reset role';empty_request:=request||jsonb_build_object('expected_composition_revision',2,'expected_composition_fingerprint',r->'fingerprint');execute 'set local role service_role';capture:=public.read_operations_scope_invoice_kernel_evidence_v1(empty_request);execute 'reset role';insert into scope_invoice_vectors values('empty_selection',capture);
 update public.operations_scope_invoice_kernel_read_gates set enabled=false;execute 'set local role service_role';begin perform public.read_operations_scope_invoice_kernel_evidence_v1(empty_request);raise exception 'revoked scope gate accepted';exception when insufficient_privilege then if sqlerrm<>'scope_invoice_read_gate_disabled' then raise;end if;end;execute 'reset role';
 begin update public.operations_scope_invoice_kernel_read_gates set organization_id='88888888-8888-4888-8888-888888888888';raise exception 'gate retargeted';exception when sqlstate '55000' then null;end;
 begin execute 'truncate public.operations_scope_invoice_kernel_read_gates';raise exception 'gate truncated';exception when sqlstate '55000' then null;end;
end;$$;
select label,evidence::text as evidence from scope_invoice_vectors order by label;
rollback;
select 'operations-scope-invoice-kernel-postgres PASS' as result;
