import {buildProjectScopeMembership,projectScopeMembershipFingerprint,serializeProjectScopeMembership,type ScopeServerCatalog} from '../../supabase/functions/_shared/canonical-project-scope.ts';
const organization_id='11111111-1111-4111-8111-111111111111',large='cccccccc-cccc-4ccc-8ccc-cccccccccccc',packing='eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee';
const catalog:ScopeServerCatalog={projects:['55555555-5555-4555-8555-555555555555','77777777-7777-4777-8777-777777777777'].map(id=>({id,organization_id,booking_id:'Legacy-Order-42',deleted_at:null})),
 large_projects:[{id:large,organization_id,primary_booking_id:'Legacy-Order-42',deleted_at:null}],packing_projects:[{id:packing,organization_id,booking_id:'Legacy-Order-42',large_project_id:large,status:'delivered'}],
 bookings:[{id:'Legacy-Order-42',organization_id,large_project_id:null}],large_project_bookings:[{id:'ffffffff-ffff-4fff-8fff-ffffffffffff',organization_id,large_project_id:large,booking_id:'Legacy-Order-42'}],
 packing_project_bookings:[{id:'12121212-1212-4212-8212-121212121212',organization_id,packing_id:packing,booking_id:'Legacy-Order-42'}],allowed_packing_statuses:['delivered']};
const initial=buildProjectScopeMembership(organization_id,'large_project',large,catalog),packingSnapshot=buildProjectScopeMembership(organization_id,'packing_project',packing,catalog),projectSnapshot=buildProjectScopeMembership(organization_id,'project',catalog.projects[0].id,catalog);
catalog.bookings.push({id:'Added-Order-9',organization_id,large_project_id:null});catalog.large_project_bookings.push({id:'23232323-2323-4232-8232-232323232323',organization_id,large_project_id:large,booking_id:'Added-Order-9'});
const added=buildProjectScopeMembership(organization_id,'large_project',large,catalog);
catalog.bookings.push({id:'\uE000',organization_id,large_project_id:null},{id:'\u{10000}',organization_id,large_project_id:null});
catalog.large_project_bookings.push({id:'56565656-5656-4565-8565-565656565656',organization_id,large_project_id:large,booking_id:'\uE000'},{id:'67676767-6767-4676-8676-676767676767',organization_id,large_project_id:large,booking_id:'\u{10000}'});
const unicode=buildProjectScopeMembership(organization_id,'large_project',large,catalog);
catalog.large_project_bookings=[];catalog.large_projects[0].primary_booking_id=null;const empty=buildProjectScopeMembership(organization_id,'large_project',large,catalog);
console.log(JSON.stringify({initial,initialRaw:serializeProjectScopeMembership(initial),initialHash:await projectScopeMembershipFingerprint(initial),packing:packingSnapshot,packingHash:await projectScopeMembershipFingerprint(packingSnapshot),project:projectSnapshot,projectHash:await projectScopeMembershipFingerprint(projectSnapshot),added,addedHash:await projectScopeMembershipFingerprint(added),unicode,unicodeRaw:serializeProjectScopeMembership(unicode),unicodeHash:await projectScopeMembershipFingerprint(unicode),empty,emptyHash:await projectScopeMembershipFingerprint(empty)}));
