-- JSON describes fixed controlled rollback mutations; no unknown dispatcher is invoked.
select jsonb_build_array(
 jsonb_build_object('label','same_count_range_semantics','mutation','update pg_catalog.pg_range set rngsubdiff=0 where rngtypid=''operations_full_catalog_fixture.metadata_range''::regtype;','section','types','identity','operations_full_catalog_fixture.metadata_range','field','descriptor_sha256'),
 jsonb_build_object('label','same_count_sql_standard_body','mutation','create or replace function operations_full_catalog_fixture.metadata_sql_standard() returns integer language sql set search_path='''' begin atomic select 2;end;','section','functions','identity','operations_full_catalog_fixture.metadata_sql_standard()','field','stored_sql_body_sha256'),
 jsonb_build_object('label','same_count_index_replica_identity','mutation','alter table operations_full_catalog_fixture.metadata_identity replica identity using index metadata_identity_alternate;','section','indices','identity','operations_full_catalog_fixture.metadata_identity_pkey','field','descriptor_sha256'),
 jsonb_build_object('label','same_count_column_storage','mutation','alter table operations_full_catalog_fixture.metadata_storage alter column value set storage external;','section','relations','identity','operations_full_catalog_fixture.metadata_storage','field','columns'),
 jsonb_build_object('label','same_count_domain_not_null','mutation','alter domain operations_full_catalog_fixture.metadata_domain set not null;','section','types','identity','operations_full_catalog_fixture.metadata_domain','field','descriptor_sha256'),
 jsonb_build_object('label','same_count_procedure_body','mutation','create or replace procedure operations_full_catalog_fixture.metadata_procedure() language sql set search_path='''' as $body$select 2;$body$;','section','functions','identity','operations_full_catalog_fixture.metadata_procedure()','field','body_sha256'),
 jsonb_build_object('label','same_count_view_definition','mutation','create or replace view operations_full_catalog_fixture.metadata_view as select value from operations_full_catalog_fixture.metadata_source_b;','section','relations','identity','operations_full_catalog_fixture.metadata_view','field','definition_sha256'),
 jsonb_build_object('label','same_count_owner','mutation','alter procedure operations_full_catalog_fixture.metadata_procedure() owner to full_catalog_fixture_owner;','section','functions','identity','operations_full_catalog_fixture.metadata_procedure()','field','owner'),
 jsonb_build_object('label','same_count_config','mutation','alter procedure operations_full_catalog_fixture.metadata_procedure() set search_path=public;','section','functions','identity','operations_full_catalog_fixture.metadata_procedure()','field','config_sha256'),
 jsonb_build_object('label','same_count_security','mutation','alter procedure operations_full_catalog_fixture.metadata_procedure() security definer;','section','functions','identity','operations_full_catalog_fixture.metadata_procedure()','field','security_definer'),
 jsonb_build_object('label','old_core_public_bypass','mutation','grant execute on function operations_economy_private.read_scope_invoice_kernel_v1(jsonb) to public;','section','functions','identity','operations_economy_private.read_scope_invoice_kernel_v1(jsonb)','field','public_execute'),
 jsonb_build_object('label','old_core_inherited_bypass','mutation','grant execute on function operations_economy_private.read_scope_invoice_kernel_v1(jsonb) to full_catalog_fixture_owner;grant full_catalog_fixture_owner to service_role;','section','functions','identity','operations_economy_private.read_scope_invoice_kernel_v1(jsonb)','field','client_execute'),
 jsonb_build_object('label','same_count_schema_usage','mutation','grant usage on schema operations_full_catalog_fixture to authenticated;','section','schemas','identity','operations_full_catalog_fixture','field','client_usage'),
 jsonb_build_object('label','same_count_extension_membership','mutation','alter extension plpgsql add procedure operations_full_catalog_fixture.metadata_procedure();','section','functions','identity','operations_full_catalog_fixture.metadata_procedure()','field','extension_membership'),
 jsonb_build_object('label','unknown_outside_namespace','mutation','create schema full_catalog_unknown;create function full_catalog_unknown.closed_dispatch() returns integer language sql set search_path='''' as $body$select 0;$body$;revoke all on function full_catalog_unknown.closed_dispatch() from public,anon,authenticated,service_role;','section','functions','identity','full_catalog_unknown.closed_dispatch()','field',null),
 jsonb_build_object('label','default_acl_drift','mutation','alter default privileges in schema operations_full_catalog_fixture grant execute on functions to authenticated;','section','defaults','identity','postgres:operations_full_catalog_fixture:f','field',null)
);
