\set ON_ERROR_STOP on
begin;
create temporary table scope_composition_fixture(data jsonb not null);
insert into scope_composition_fixture values(:'fixture'::jsonb);
grant select on scope_composition_fixture to authenticated,service_role;
create function pg_temp.composition_assert(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'composition assertion failed: %',label;end if;end;$$;
create function pg_temp.composition_fail_capture() returns trigger language plpgsql as $$begin raise exception 'synthetic composition capture failure' using errcode='22023';end;$$;
insert into public.operations_finance_invoice_enrollments values('fixture_comp_source','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_invoice_project_scopes values('fixture_comp_source','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true);
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
do $$declare f jsonb;p jsonb;r jsonb;preview jsonb;scope_command jsonb;command jsonb;bind jsonb;policy jsonb;first jsonb;document jsonb;
 baseline1 uuid;baseline2 uuid;binding uuid;source_snapshot uuid;extra_baseline uuid;other_snapshot uuid;org uuid:='11111111-1111-4111-8111-111111111111';scope uuid:='90909090-9090-4909-8909-909090909090';project uuid:='55555555-5555-4555-8555-555555555555';obligation uuid:='abababab-abab-4aba-8aba-abababababab';anchor text;begin
 select data into f from scope_composition_fixture;p:=f->'baseline';anchor:=f->>'anchor';execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_comp_source',floor(extract(epoch from clock_timestamp()))::bigint::text,'fixture_comp_original_nonce',f->>'rawInvoice');source_snapshot:=(r->>'snapshot_receipt_id')::uuid;execute 'reset role';
 execute 'set local role authenticated';preview:=public.preview_operations_project_scope_v1('large_project','cccccccc-cccc-4ccc-8ccc-cccccccccccc');
 scope_command:=jsonb_build_object('schema','operations-project-scope-enroll.v1','economic_scope_id',scope,'root_kind','large_project','root_id','cccccccc-cccc-4ccc-8ccc-cccccccccccc','expected_revision',0,'expected_membership_fingerprint',preview->>'membership_fingerprint','idempotency_key','synthetic-composition-enrollment','reason','Capture actual whole-scope members');perform public.enroll_operations_project_scope_v1(scope_command);
 r:=public.append_operations_manual_obligation_baseline_v1(p);baseline1:=(r->>'event_id')::uuid;
 r:=public.append_operations_manual_obligation_baseline_v1(p||jsonb_build_object('project_id','77777777-7777-4777-8777-777777777777','obligation_id','cdcdcdcd-cdcd-4cdc-8cdc-cdcdcdcdcdcd','category','personnel','cost_basis','time','estimate_minor',500000,'committed_minor',200000,'idempotency_key','synthetic-composition-child-two'));baseline2:=(r->>'event_id')::uuid;
 bind:=jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',source_snapshot,'source_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_economic_revision',1,'expected_economic_fingerprint',repeat('a',64),'idempotency_key','synthetic-composition-binding','reason','Bind observed actual original');r:=public.bind_operations_invoice_obligation_v1(bind);binding:=(r->>'event_id')::uuid;
 policy:=jsonb_build_object('schema_version','operations-obligation-source-policy.v1','project_id',project,'obligation_id',obligation,'baseline_event_id',baseline1,'binding_event_id',binding,'expected_policy_revision',0,'replaces_estimate_minor',540000,'consumes_commitment_minor',null,'idempotency_key','synthetic-composition-policy','reason','Explicit replacement, unknown commitment');perform public.append_operations_obligation_source_policy_v1(policy);
 command:=jsonb_build_object('schema_version','operations-scope-obligation-compose.v1','economic_scope_id',scope,'expected_scope_revision',1,'expected_membership_fingerprint',preview->>'membership_fingerprint','expected_composition_revision',0,'currency','SEK','baseline_event_ids',jsonb_build_array(baseline1,baseline2),'idempotency_key','synthetic-composition-first','reason','Compose actual selected local authority only');
 r:=public.compose_operations_scope_obligations_v1(command||'{"expected_composition_revision":1}');perform pg_temp.composition_assert(r->>'outcome'='stale' and r->>'current_composition_revision'='0','first stale has no ghost');execute 'reset role';perform pg_temp.composition_assert(not exists(select 1 from public.operations_scope_obligation_composition_heads),'no ghost composition');execute 'set local role authenticated';
 for r in select value from jsonb_array_elements(jsonb_build_array(command||'{"budget_minor":100}',command||'{"coverage":"complete"}',command||'{"expected_scope_revision":"1"}',command||jsonb_build_object('baseline_event_ids',jsonb_build_array(baseline1,baseline1)))) loop begin perform public.compose_operations_scope_obligations_v1(r);raise exception 'invalid composition accepted';exception when sqlstate '22023' then null;end;end loop;
 begin perform public.compose_operations_scope_obligations_v1(command||'{"currency":"EUR"}');raise exception 'local currency relabelled';exception when sqlstate '22023' then if sqlerrm<>'current_member_local_baseline_required' then raise;end if;end;
 execute 'reset role';insert into public.projects(id,organization_id,deleted_at) values('81818181-8181-4818-8818-818181818181',org,null);execute 'set local role authenticated';
 r:=public.append_operations_manual_obligation_baseline_v1(p||jsonb_build_object('project_id','81818181-8181-4818-8818-818181818181','obligation_id','efefefef-efef-4efe-8efe-efefefefefef','idempotency_key','synthetic-composition-nonmember-baseline'));extra_baseline:=(r->>'event_id')::uuid;
 begin perform public.compose_operations_scope_obligations_v1(command||jsonb_build_object('baseline_event_ids',jsonb_build_array(extra_baseline)));raise exception 'same-org nonmember local project composed';exception when sqlstate '22023' then if sqlerrm<>'current_member_local_baseline_required' then raise;end if;end;
 preview:=public.preview_operations_project_scope_v1('project','81818181-8181-4818-8818-818181818181');perform public.enroll_operations_project_scope_v1(scope_command||jsonb_build_object('economic_scope_id','82828282-8282-4828-8828-828282828282','root_kind','project','root_id','81818181-8181-4818-8818-818181818181','expected_membership_fingerprint',preview->>'membership_fingerprint','idempotency_key','synthetic-composition-other-scope'));
 r:=public.compose_operations_scope_obligations_v1(command||jsonb_build_object('economic_scope_id','82828282-8282-4828-8828-828282828282','expected_membership_fingerprint',preview->>'membership_fingerprint','baseline_event_ids','[]'::jsonb,'idempotency_key','synthetic-composition-other-empty'));other_snapshot:=(r->>'snapshot_id')::uuid;execute 'reset role';
 -- Inject a conflicting pre-existing reservation as a controlled DB fault;
 -- actual authenticated composition must reject it and roll back, not transfer.
 begin
 insert into public.operations_scope_obligation_ownership values(org,obligation,'82828282-8282-4828-8828-828282828282',other_snapshot);execute 'set local role authenticated';
 begin perform public.compose_operations_scope_obligations_v1(command);raise exception 'cross-scope obligation reservation ignored';exception when unique_violation then if sqlerrm<>'scope_obligation_owner_conflict' then raise;end if;end;execute 'reset role';
 raise exception 'synthetic composition owner rollback' using errcode='22023';exception when sqlstate '22023' then if sqlerrm<>'synthetic composition owner rollback' then raise;end if;end;
 execute 'reset role';execute 'create trigger synthetic_composition_rollback before insert on public.operations_scope_obligation_baseline_captures for each row execute function pg_temp.composition_fail_capture()';execute 'set local role authenticated';
 begin perform public.compose_operations_scope_obligations_v1(command);raise exception 'injected composition failure';exception when sqlstate '22023' then if sqlerrm<>'synthetic composition capture failure' then raise;end if;end;
 execute 'reset role';perform pg_temp.composition_assert(not exists(select 1 from public.operations_scope_obligation_composition_heads where economic_scope_id=scope) and not exists(select 1 from public.operations_scope_obligation_compositions where economic_scope_id=scope) and not exists(select 1 from public.operations_scope_obligation_ownership),'head snapshot ownership captures atomic rollback');execute 'drop trigger synthetic_composition_rollback on public.operations_scope_obligation_baseline_captures';execute 'set local role authenticated';
 first:=public.compose_operations_scope_obligations_v1(command);r:=public.compose_operations_scope_obligations_v1(command);perform pg_temp.composition_assert(first->>'outcome'='accepted' and r->>'outcome'='replayed' and r->>'snapshot_id'=first->>'snapshot_id','actual whole-scope composition exact replay');
 begin perform public.compose_operations_scope_obligations_v1(command||'{"reason":"Changed same key composition"}');raise exception 'changed composition key';exception when unique_violation then if sqlerrm<>'scope_composition_idempotency_conflict' then raise;end if;end;execute 'reset role';
 select c.document into document from public.operations_scope_obligation_compositions c where c.snapshot_id=(first->>'snapshot_id')::uuid;
 perform pg_temp.composition_assert(document->>'selected_count'='2' and document->>'known_estimate_minor'='1500000' and document->>'known_commitment_minor'='200000' and document->'all_selected_estimates_known'='true' and document->'all_selected_commitments_known'='false','only known manual child baselines summed, unknown remains unknown');
 perform pg_temp.composition_assert(document->>'coverage'='unavailable' and document->'eac_minor'='null' and document->'budget_minor'='null' and document->>'authority_scope'='canonical_scope_composition' and jsonb_array_length(document->'source_inventory')=1,'dedup actual source once and no whole-budget/EAC invented');
 perform pg_temp.composition_assert(document#>>'{source_inventory,0,observed_amount_minor}'='540000' and document#>>'{source_inventory,0,source_policy_state}'='current' and document#>>'{category_coverage,supplier}'='unavailable','saved source proof does not declare complete supplier inventory');
 execute 'set local role service_role';r:=public.read_operations_scope_obligation_composition_v1(org,scope);perform pg_temp.composition_assert(r->'scope_membership_current'='true' and r->'baseline_references_current'='true' and r->'source_references_current'='true' and r->>'coverage'='unavailable','read only captured-reference currentness, costs still unavailable');execute 'reset role';
 -- A policy revision invalidates the saved source-reference capture without
 -- recalculating money or changing the immutable composition.
 execute 'set local role authenticated';perform public.append_operations_obligation_source_policy_v1(policy||'{"expected_policy_revision":1,"replaces_estimate_minor":500000,"idempotency_key":"synthetic-composition-policy-revised"}');execute 'reset role';execute 'set local role service_role';r:=public.read_operations_scope_obligation_composition_v1(org,scope);perform pg_temp.composition_assert(r->'source_references_current'='false' and r->'document'=document,'policy change preserves immutable historical composition');execute 'reset role';
 -- Source graph additions require re-enrollment; selected local baselines cannot
 -- prove that newly added/unbound sources are fully represented.
 insert into public.bookings values('Added-Order-9',org,null);insert into public.large_project_bookings values('23232323-2323-4232-8232-232323232323',org,'cccccccc-cccc-4ccc-8ccc-cccccccccccc','Added-Order-9');execute 'set local role authenticated';
 begin perform public.compose_operations_scope_obligations_v1(command||'{"expected_composition_revision":1,"idempotency_key":"synthetic-composition-stale-graph"}');raise exception 'changed graph old scope accepted';exception when sqlstate '22023' then if sqlerrm<>'current_scope_membership_required' then raise;end if;end;execute 'reset role';execute 'set local role service_role';r:=public.read_operations_scope_obligation_composition_v1(org,scope);perform pg_temp.composition_assert(r->'scope_membership_current'='false','actual graph currentness rechecked');execute 'reset role';execute 'set local role authenticated';preview:=public.preview_operations_project_scope_v1('large_project','cccccccc-cccc-4ccc-8ccc-cccccccccccc');perform public.enroll_operations_project_scope_v1(scope_command||jsonb_build_object('expected_revision',1,'expected_membership_fingerprint',preview->>'membership_fingerprint','idempotency_key','synthetic-composition-scope-revised'));
 command:=command||jsonb_build_object('expected_scope_revision',2,'expected_membership_fingerprint',preview->>'membership_fingerprint','expected_composition_revision',1,'baseline_event_ids','[]'::jsonb,'idempotency_key','synthetic-composition-empty');perform public.compose_operations_scope_obligations_v1(command);execute 'reset role';
 select c.document into document from public.operations_scope_obligation_compositions c where composition_revision=2;
 perform pg_temp.composition_assert(document->>'selected_count'='0' and document->'known_estimate_minor'='null' and document->'known_commitment_minor'='null' and document->'all_selected_estimates_known'='false' and document->'eac_minor'='null','empty selected catalog is unknown, never0');
 perform pg_temp.composition_assert((select count(*) from public.operations_scope_obligation_ownership)=2,'removal does not release obligation ownership');
 execute 'set local role authenticated';perform public.append_operations_manual_obligation_baseline_v1(p||'{"expected_revision":1,"estimate_minor":1100000,"idempotency_key":"synthetic-composition-baseline-revised"}');
 begin perform public.compose_operations_scope_obligations_v1(command||jsonb_build_object('expected_composition_revision',2,'baseline_event_ids',jsonb_build_array(baseline1),'idempotency_key','synthetic-composition-stale-baseline'));raise exception 'old local baseline composed';exception when sqlstate '22023' then if sqlerrm<>'current_member_local_baseline_required' then raise;end if;end;
 begin perform public.read_operations_scope_obligation_composition_v1(org,scope);raise exception 'client invokes service reader';exception when insufficient_privilege then null;end;execute 'reset role';
 perform set_config('request.jwt.claims','{"sub":"cccccccc-cccc-4ccc-8ccc-cccccccccccc","role":"authenticated"}',true);execute 'set local role authenticated';begin perform public.compose_operations_scope_obligations_v1(command);raise exception 'foreign admin composition';exception when insufficient_privilege then if sqlerrm<>'enrolled_canonical_scope_required' then raise;end if;end;execute 'reset role';
 perform set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);delete from public.user_roles where user_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and role='admin';execute 'set local role authenticated';begin perform public.compose_operations_scope_obligations_v1(command);raise exception 'revoked admin composition replay';exception when insufficient_privilege then null;end;execute 'reset role';
 begin update public.operations_scope_obligation_compositions set document='{}';raise exception 'composition rewrite';exception when sqlstate '55000' then null;end;
 begin delete from public.operations_scope_obligation_ownership;raise exception 'ownership released';exception when sqlstate '55000' then null;end;
 begin update public.operations_scope_obligation_composition_heads set current_revision=1;raise exception 'composition rewind';exception when sqlstate '55000' then if sqlerrm<>'scope_composition_head_change_denied' then raise;end if;end;
 begin execute 'truncate public.operations_scope_obligation_composition_heads cascade';raise exception 'composition truncated';exception when sqlstate '55000' then null;end;
end;$$;
rollback;
select 'operations-scope-obligation-composition-postgres PASS' as result;
