\set ON_ERROR_STOP on
-- Exact immutable authority fixture produced by operations-obligation-fixture.ts.
-- All source evidence arrives through actual service receiver RPCs; transaction rolls back.
begin;
create temporary table kernel_fixture(data jsonb not null);
insert into kernel_fixture values(:'fixture'::jsonb);
grant select on kernel_fixture to authenticated,service_role;
create temporary table kernel_vectors(label text primary key,evidence jsonb not null);
create function pg_temp.kernel_assert(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'kernel assertion failed: %',label;end if;end;$$;
create function pg_temp.credit_fail_event() returns trigger language plpgsql as $$begin raise exception 'synthetic own credit atomic failure' using errcode='22023';end;$$;
insert into public.operations_finance_invoice_enrollments values('fixture_own_credit_v1','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_invoice_project_scopes values('fixture_own_credit_v1','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true);
insert into public.operations_finance_credit_v2_enrollments values('fixture_own_credit_v2','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_credit_v2_project_scopes values('fixture_own_credit_v2','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true);
set local role service_role;
do $$declare f jsonb;r jsonb;begin select data into f from kernel_fixture;
 r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_own_credit_v1',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_own_credit_original',f->>'rawInvoice');
 perform pg_temp.kernel_assert(r->>'outcome'='accepted','real original receiver');end;$$;
reset role;
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
do $$declare f jsonb;p jsonb;credit jsonb;command jsonb;bind jsonb;r jsonb;first jsonb;orig_snapshot uuid;credit_snapshot uuid;binding uuid;anchor text;original_anchor text;
 org uuid:='11111111-1111-4111-8111-111111111111';project uuid:='55555555-5555-4555-8555-555555555555';obligation uuid:='abababab-abab-4aba-8aba-abababababab';begin
 select data into f from kernel_fixture;select id into orig_snapshot from public.operations_finance_invoice_snapshots where source_revision=1;
 original_anchor:=f->>'anchor';
 execute 'set local role authenticated';perform public.append_operations_manual_obligation_baseline_v1(f->'baseline');
 bind:=jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',orig_snapshot,'source_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_economic_revision',1,'expected_economic_fingerprint',repeat('a',64),'idempotency_key','synthetic-kernel-original-bind','reason','Actual positive bound invoice source');
 first:=public.bind_operations_invoice_obligation_v1(bind);binding:=(first->>'event_id')::uuid;execute 'reset role';
 command:=jsonb_build_object('schema_version','operations-invoice-obligation-kernel-read.v1','organization_id',org,'project_id',project,'obligation_id',obligation);
 execute 'set local role service_role';begin perform public.read_operations_invoice_obligation_kernel_evidence_v1(command);raise exception 'default-off kernel read accepted';exception when insufficient_privilege then if sqlerrm<>'invoice_kernel_read_gate_disabled' then raise;end if;end;execute 'reset role';
 insert into public.operations_invoice_obligation_kernel_read_gates(organization_id) values(org);perform pg_temp.kernel_assert((select not enabled from public.operations_invoice_obligation_kernel_read_gates),'read gate defaults false');update public.operations_invoice_obligation_kernel_read_gates set enabled=true;
 execute 'set local role service_role';r:=public.read_operations_invoice_obligation_kernel_evidence_v1(command);perform pg_temp.kernel_assert(r->>'state'='captured' and r#>>'{sources,0,resolved}'='true' and r#>>'{sources,0,amount_minor}'='540000' and r#>>'{sources,0,status}'='preliminary' and r#>>'{sources,0,policy_state}'='missing' and r#>'{sources,0,replaces_estimate_minor}'='null' and r#>'{baseline,committed_minor}'='null','actual paid booked invoice remains preliminary and missing policy/commitment stay null');execute 'reset role';
 insert into kernel_vectors values('missing_policy',r);
 select event_id into orig_snapshot from public.operations_project_obligation_baselines where organization_id=org and obligation_id=obligation;
 execute 'set local role authenticated';perform public.append_operations_obligation_source_policy_v1(jsonb_build_object('schema_version','operations-obligation-source-policy.v1','project_id',project,'obligation_id',obligation,'baseline_event_id',orig_snapshot,'binding_event_id',binding,'expected_policy_revision',0,'replaces_estimate_minor',700000,'consumes_commitment_minor',null,'idempotency_key','synthetic-kernel-source-policy','reason','Explicit planned variance replacement policy'));execute 'reset role';
 execute 'set local role service_role';r:=public.read_operations_invoice_obligation_kernel_evidence_v1(command);perform pg_temp.kernel_assert(r#>>'{sources,0,policy_state}'='current' and r#>>'{sources,0,replaces_estimate_minor}'='700000' and r#>'{sources,0,consumes_commitment_minor}'='null' and r->>'category_coverage'='unavailable' and r->'eac_minor'='null','planned variance copied without invented observed cost cap/EAC');execute 'reset role';insert into kernel_vectors values('current_policy',r);
 -- Equal V2 metadata enriches proof without changing copied V1 economics/policy.
 p:=f->'invoice'||jsonb_build_object('schema_version','finance-project-invoice-destination-v2','source_economic_revision',1,'source_economic_publication_fingerprint',repeat('a',64),'source_publication_fingerprint',repeat('e',64),'credit_relationship_fingerprint',null,'allocations',jsonb_build_array((f#>'{invoice,allocations,0}')||jsonb_build_object('source_anchor',f->>'anchor','credited_source_anchor',null)));
 execute 'set local role service_role';perform public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_kernel_original_v2_same',p::text);r:=public.read_operations_invoice_obligation_kernel_evidence_v1(command);perform pg_temp.kernel_assert(r#>>'{sources,0,resolved}'='true' and r#>>'{sources,0,amount_minor}'='540000' and r#>>'{sources,0,policy_state}'='current','coequal V2 metadata preserves genuine positive source money');execute 'reset role';insert into kernel_vectors values('coequal_v2',r);
 -- New V2 economics with older V1 bound source must not reuse old money.
 p:=jsonb_set(p||jsonb_build_object('source_revision',2,'source_economic_revision',2,'source_economic_publication_fingerprint',repeat('d',64),'source_publication_fingerprint',repeat('c',64),'recipient_net_minor',450000),'{allocations,0,amount_minor}','450000');
 execute 'set local role service_role';perform public.operations_receive_finance_project_invoice_destination_v2('fixture_own_credit_v2',floor(extract(epoch from clock_timestamp()))::bigint::text,'synthetic_kernel_original_v2_new',p::text);r:=public.read_operations_invoice_obligation_kernel_evidence_v1(command);perform pg_temp.kernel_assert(r#>>'{sources,0,resolved}'='false' and r#>'{sources,0,amount_minor}'='null' and r#>>'{sources,0,policy_state}'='stale' and r#>'{sources,0,replaces_estimate_minor}'='null','newer V2 source invalidates captured positive price and policy');execute 'reset role';insert into kernel_vectors values('newer_v2',r);
 execute 'set local role authenticated';perform public.append_operations_manual_obligation_baseline_v1(f->'baseline'||jsonb_build_object('obligation_id','cdcdcdcd-cdcd-4cdc-8cdc-cdcdcdcdcdcd','idempotency_key','synthetic-kernel-empty-baseline'));perform public.append_operations_manual_obligation_baseline_v1(f->'baseline'||jsonb_build_object('obligation_id','dededede-dede-4ded-8ded-dededededede','cost_basis','time','category','catering','idempotency_key','synthetic-kernel-time-baseline'));execute 'reset role';
 execute 'set local role service_role';r:=public.read_operations_invoice_obligation_kernel_evidence_v1(command||jsonb_build_object('obligation_id','cdcdcdcd-cdcd-4cdc-8cdc-cdcdcdcdcdcd'));perform pg_temp.kernel_assert(r->'sources'='[]' and r->'eac_minor'='null','empty captured catalog is incomplete');execute 'reset role';insert into kernel_vectors values('empty_catalog',r);
 execute 'set local role service_role';r:=public.read_operations_invoice_obligation_kernel_evidence_v1(command||jsonb_build_object('obligation_id','dededede-dede-4ded-8ded-dededededede'));perform pg_temp.kernel_assert(r->>'state'='unsupported_basis' and r->'sources'='[]','native time/Catering not priced by invoice mapper');execute 'reset role';insert into kernel_vectors values('time_basis',r);
 execute 'set local role service_role';begin perform public.read_operations_invoice_obligation_kernel_evidence_v1(command||'{"amount_minor":0}');raise exception 'caller kernel money accepted';exception when sqlstate '22023' then null;end;begin perform public.read_operations_invoice_obligation_kernel_evidence_v1(command||jsonb_build_object('project_id','77777777-7777-4777-8777-777777777777'));raise exception 'obligation retargeted';exception when sqlstate '22023' then if sqlerrm<>'actual_invoice_kernel_obligation_required' then raise;end if;end;execute 'reset role';
 execute 'set local role authenticated';begin perform public.read_operations_invoice_obligation_kernel_evidence_v1(command);raise exception 'authenticated direct service read allowed';exception when insufficient_privilege then null;end;execute 'reset role';
 update public.operations_invoice_obligation_kernel_read_gates set enabled=false;execute 'set local role service_role';begin perform public.read_operations_invoice_obligation_kernel_evidence_v1(command);raise exception 'revoked read gate accepted';exception when insufficient_privilege then if sqlerrm<>'invoice_kernel_read_gate_disabled' then raise;end if;end;execute 'reset role';
end;$$;
select label,evidence::text from kernel_vectors order by label;
rollback;
select 'operations-invoice-obligation-kernel-postgres PASS' as result;
