\set ON_ERROR_STOP on
begin;
create temporary table source_policy_fixture(data jsonb not null);
insert into source_policy_fixture values(:'fixture'::jsonb);
grant select on source_policy_fixture to authenticated,service_role;
create function pg_temp.policy_assert(v boolean,label text) returns void language plpgsql as $$begin if v is distinct from true then raise exception 'source policy assertion failed: %',label;end if;end;$$;
create function pg_temp.policy_fail_insert() returns trigger language plpgsql as $$begin raise exception 'synthetic source policy failure' using errcode='22023';end;$$;
insert into public.operations_finance_invoice_enrollments values('fixture_policy_source','99999999-9999-4999-8999-999999999999','11111111-1111-4111-8111-111111111111',true,now());
insert into public.operations_finance_invoice_project_scopes values('fixture_policy_source','56565656-5656-4565-8565-565656565656','55555555-5555-4555-8555-555555555555',true);
select set_config('request.jwt.claims','{"sub":"aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa","role":"authenticated"}',true);
do $$declare f jsonb;baseline jsonb;command jsonb;bind jsonb;bind2 jsonb;r jsonb;first jsonb;invoice jsonb;original jsonb;baseline_id uuid;binding_id uuid;binding2_id uuid;policy1 jsonb;policy2 jsonb;stamp text:=floor(extract(epoch from clock_timestamp()))::bigint::text;
 org uuid:='11111111-1111-4111-8111-111111111111';project uuid:='55555555-5555-4555-8555-555555555555';obligation uuid:='abababab-abab-4aba-8aba-abababababab';anchor text;anchor2 text;begin
 select data into f from source_policy_fixture;baseline:=f->'baseline';anchor:=f->>'anchor';
 execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_policy_source',stamp,'fixture_policy_initial_nonce',f->>'rawInvoice');execute 'reset role';
 bind:=jsonb_build_object('schema_version','operations-obligation-invoice-bind.v1','project_id',project,'obligation_id',obligation,'expected_obligation_revision',1,'source_snapshot_id',r->>'snapshot_receipt_id','source_allocation_id',f#>>'{invoice,allocations,0,allocation_id}','expected_economic_revision',1,'expected_economic_fingerprint',repeat('a',64),'idempotency_key','synthetic-policy-bind-first','reason','Bind real saved original');
 execute 'set local role authenticated';r:=public.append_operations_manual_obligation_baseline_v1(baseline);baseline_id:=(r->>'event_id')::uuid;r:=public.bind_operations_invoice_obligation_v1(bind);binding_id:=(r->>'event_id')::uuid;
 command:=jsonb_build_object('schema_version','operations-obligation-source-policy.v1','project_id',project,'obligation_id',obligation,'baseline_event_id',baseline_id,'binding_event_id',binding_id,'expected_policy_revision',0,'replaces_estimate_minor',540000,'consumes_commitment_minor',null,'idempotency_key','synthetic-policy-first','reason','Explicit source replacement, unknown commitment');
 for r in select value from jsonb_array_elements(jsonb_build_array(command||'{"amount_minor":1}',command||'{"source_status":"confirmed"}',command||'{"consumes_commitment_minor":true}',command||'{"replaces_estimate_minor":"540000"}',command||'{"expected_policy_revision":9007199254740991}')) loop
 begin perform public.append_operations_obligation_source_policy_v1(r);raise exception 'malformed policy accepted';exception when sqlstate '22023' then null;end;end loop;
 begin perform public.append_operations_obligation_source_policy_v1(command||'{"consumes_commitment_minor":0}');raise exception 'unknown commitment became explicit zero';exception when sqlstate '22023' then if sqlerrm<>'unknown_commitment_policy_must_remain_null' then raise;end if;end;
 r:=public.append_operations_obligation_source_policy_v1(command||'{"expected_policy_revision":1}');perform pg_temp.policy_assert(r->>'outcome'='stale' and r->>'current_policy_revision'='0','stale new policy no ghost');
 execute 'reset role';perform pg_temp.policy_assert(not exists(select 1 from public.operations_obligation_source_policy_heads),'stale no head');execute 'create trigger synthetic_policy_rollback before insert on public.operations_obligation_source_policies for each row execute function pg_temp.policy_fail_insert()';execute 'set local role authenticated';
 begin perform public.append_operations_obligation_source_policy_v1(command);raise exception 'injected policy failure accepted';exception when sqlstate '22023' then if sqlerrm<>'synthetic source policy failure' then raise;end if;end;
 execute 'reset role';perform pg_temp.policy_assert(not exists(select 1 from public.operations_obligation_source_policy_heads) and not exists(select 1 from public.operations_obligation_source_policies),'atomic policy/head rollback');execute 'drop trigger synthetic_policy_rollback on public.operations_obligation_source_policies';execute 'set local role authenticated';
 first:=public.append_operations_obligation_source_policy_v1(command);perform pg_temp.policy_assert(first->>'outcome'='accepted' and first->>'policy_revision'='1' and first->'credit_eligible'='false' and first->'eac_minor'='null','saved explicit decision is not EAC eligibility');
 r:=public.append_operations_obligation_source_policy_v1(command);perform pg_temp.policy_assert(r->>'outcome'='replayed' and r->>'event_id'=first->>'event_id','exact policy replay');
 begin perform public.append_operations_obligation_source_policy_v1(command||'{"reason":"Changed same key policy"}');raise exception 'policy idempotency changed';exception when unique_violation then if sqlerrm<>'source_policy_idempotency_conflict' then raise;end if;end;
 execute 'reset role';execute 'set local role service_role';r:=public.read_operations_obligation_source_policy_v1(org,project,obligation,anchor);perform pg_temp.policy_assert(r->>'policy_state'='current' and r->>'replaces_estimate_minor'='540000' and r->'consumes_commitment_minor'='null' and r->>'remaining_coverage'='unavailable' and r->>'authority_scope'='local_project_only','policy projection preserves unknown remaining');execute 'reset role';
 -- Metadata/source correction never releases existing baseline reservation.
 invoice:=f->'invoice'||jsonb_build_object('source_revision',2,'source_publication_fingerprint',repeat('c',64),'invoice_status','rejected');invoice:=jsonb_set(invoice,'{allocations,0,status}','"rejected"');execute 'set local role service_role';perform public.operations_receive_finance_project_invoice_destination_v1('fixture_policy_source',stamp,'fixture_policy_rejected_nonce',invoice::text);
 r:=public.read_operations_obligation_source_policy_v1(org,project,obligation,anchor);perform pg_temp.policy_assert(r->>'policy_state'='unresolved' and r->>'reason'='changed_invoice_economics' and r->'eac_minor'='null','source change makes policy stale without reinterpretation');execute 'reset role';execute 'set local role authenticated';
 begin perform public.append_operations_obligation_source_policy_v1(command||'{"expected_policy_revision":1,"idempotency_key":"synthetic-policy-stale-source"}');raise exception 'stale source new decision';exception when sqlstate '22023' then if sqlerrm<>'current_source_policy_evidence_required' then raise;end if;end;execute 'reset role';
 invoice:=f->'invoice'||jsonb_build_object('invoice_id','78787878-7878-4787-8787-787878787878','recipient_net_minor',500000);invoice:=jsonb_set(jsonb_set(invoice,'{allocations,0,allocation_id}','"89898989-8989-4898-8989-898989898989"'),'{allocations,0,amount_minor}','500000');execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_policy_source',stamp,'fixture_policy_second_invoice',invoice::text);execute 'reset role';
 bind2:=bind||jsonb_build_object('source_snapshot_id',r->>'snapshot_receipt_id','source_allocation_id','89898989-8989-4898-8989-898989898989','idempotency_key','synthetic-policy-bind-second');execute 'set local role authenticated';r:=public.bind_operations_invoice_obligation_v1(bind2);binding2_id:=(r->>'event_id')::uuid;anchor2:=r->>'source_anchor';
 policy2:=command||jsonb_build_object('binding_event_id',binding2_id,'replaces_estimate_minor',460001,'idempotency_key','synthetic-policy-second-too-much');
 begin perform public.append_operations_obligation_source_policy_v1(policy2);raise exception 'stale first reservation released';exception when sqlstate '22023' then if sqlerrm<>'source_policy_baseline_aggregate_exceeded' then raise;end if;end;
 policy2:=policy2||'{"replaces_estimate_minor":460000,"idempotency_key":"synthetic-policy-second-exact"}';perform public.append_operations_obligation_source_policy_v1(policy2);execute 'reset role';
 -- A distinct explicit baseline is needed to record newly known commitment.
 invoice:=f->'invoice'||jsonb_build_object('source_revision',3,'source_publication_fingerprint',repeat('d',64),'invoice_status','approved');invoice:=jsonb_set(invoice,'{allocations,0,status}','"confirmed"');execute 'set local role service_role';r:=public.operations_receive_finance_project_invoice_destination_v1('fixture_policy_source',stamp,'fixture_policy_first_confirmed',invoice::text);execute 'reset role';
 bind:=bind||jsonb_build_object('source_snapshot_id',r->>'snapshot_receipt_id','expected_economic_revision',3,'expected_economic_fingerprint',repeat('d',64),'expected_obligation_revision',2,'idempotency_key','synthetic-policy-bind-revised');execute 'set local role authenticated';r:=public.append_operations_manual_obligation_baseline_v1(baseline||'{"expected_revision":1,"committed_minor":800000,"idempotency_key":"synthetic-policy-known-commitment"}');baseline_id:=(r->>'event_id')::uuid;
 r:=public.bind_operations_invoice_obligation_v1(bind);binding_id:=(r->>'event_id')::uuid;perform public.bind_operations_invoice_obligation_v1(bind2||'{"expected_obligation_revision":2,"idempotency_key":"synthetic-policy-second-rebind"}');execute 'reset role';select event_id into binding2_id from public.operations_project_obligation_invoice_bindings where source_anchor=anchor2 order by binding_sequence desc limit 1;execute 'set local role authenticated';
 policy1:=command||jsonb_build_object('baseline_event_id',baseline_id,'binding_event_id',binding_id,'expected_policy_revision',1,'replaces_estimate_minor',700000,'consumes_commitment_minor',700000,'idempotency_key','synthetic-policy-revised-first');
 r:=public.append_operations_obligation_source_policy_v1(policy1);perform pg_temp.policy_assert(r->>'policy_revision'='2','reviewed replacement may differ from observed invoice, no invented pricing cap');
 policy2:=policy2||jsonb_build_object('baseline_event_id',baseline_id,'binding_event_id',binding2_id,'expected_policy_revision',1,'replaces_estimate_minor',300000,'consumes_commitment_minor',100001,'idempotency_key','synthetic-policy-commitment-over');
 begin perform public.append_operations_obligation_source_policy_v1(policy2);raise exception 'aggregate commitment exceeded';exception when sqlstate '22023' then if sqlerrm<>'source_policy_baseline_aggregate_exceeded' then raise;end if;end;
 perform public.append_operations_obligation_source_policy_v1(policy2||'{"consumes_commitment_minor":100000,"idempotency_key":"synthetic-policy-commitment-exact"}');execute 'reset role';
 perform pg_temp.policy_assert((select count(*) from public.operations_obligation_source_policies)=4,'history appends, old reservations retained');
 execute 'set local role service_role';r:=public.read_operations_obligation_source_policy_v1(org,project,obligation,anchor);perform pg_temp.policy_assert(r->>'policy_state'='current' and r->>'consumes_commitment_minor'='700000' and r->'credit_eligible'='false' and r->'eac_minor'='null' and r->>'source_currentness'='receiver_v1_only','known policy still does not prove full project or v2 source');execute 'reset role';
 -- Revocation, client isolation and immutable evidence/head guards.
 delete from public.user_roles where user_id='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa' and role='admin';execute 'set local role authenticated';begin perform public.append_operations_obligation_source_policy_v1(command);raise exception 'revoked policy replay';exception when insufficient_privilege then null;end;
 begin perform 1 from public.operations_obligation_source_policies;raise exception 'client policy table access';exception when insufficient_privilege then null;end;execute 'reset role';
 begin update public.operations_obligation_source_policies set consumes_commitment_minor=0;raise exception 'saved policy changed';exception when sqlstate '55000' then null;end;
 begin delete from public.operations_obligation_source_policy_heads;raise exception 'policy head released';exception when sqlstate '55000' then if sqlerrm<>'source_policy_head_change_denied' then raise;end if;end;
 begin update public.operations_obligation_source_policy_heads set current_revision=1;raise exception 'policy head rewind';exception when sqlstate '55000' then if sqlerrm<>'source_policy_head_change_denied' then raise;end if;end;
 begin execute 'truncate public.operations_obligation_source_policy_heads cascade';raise exception 'policy truncated';exception when sqlstate '55000' then null;end;
end;$$;
rollback;
select 'operations-obligation-source-policy-postgres PASS' as result;
