-- NEW TEST ONLY copied fixture facts and accepted metadata; no pricing or sum.
begin;set local time zone 'UTC';set local datestyle='ISO, YMD';
do $$begin
 if current_database() not in ('eventflow_own_credit_reverse_remaining_six','eventflow_own_credit_capacity_reverse_remaining_six')
 or current_setting('test.remaining_six_credit_cap_reverse_isolated',true) is distinct from 'synthetic-disposable'
 then raise exception 'credit_cap_reverse_neutrality_isolated_required' using errcode='42501';end if;
end$$;
select jsonb_build_object(
 'schema','remaining-six-credit-capacity-reverse-neutrality.v1',
 'baseline',(select jsonb_build_object('event_id',event_id,'revision',revision,'currency',currency,'estimate_minor',estimate_minor,'committed_minor',committed_minor,'fingerprint',fingerprint) from public.operations_project_obligation_baselines where organization_id='11111111-1111-4111-8111-111111111111' and obligation_id='abababab-abab-4aba-8aba-abababababab'),
 'binding',(select jsonb_build_object('event_id',event_id,'baseline_event_id',baseline_event_id,'source_anchor',source_anchor,'currency',currency,'amount_minor',amount_minor,'source_snapshot_id',source_snapshot_id,'source_raw_body_sha256',source_raw_body_sha256,'source_economic_revision',source_economic_revision) from public.operations_project_obligation_invoice_bindings where organization_id='11111111-1111-4111-8111-111111111111' and obligation_id='abababab-abab-4aba-8aba-abababababab'),
 'v1_original',(select jsonb_build_object('id',s.id,'current_revision',h.current_revision,'body_sha256',s.body_sha256,'currency',s.envelope->'currency','net_minor',s.envelope->'recipient_net_minor','allocation_minor',s.envelope#>'{allocations,0,amount_minor}','allocation_count',jsonb_array_length(s.envelope->'allocations'),'accounting_state',s.envelope->'accounting_state','settlement_state',s.envelope->'settlement_state','provider_approval_state',s.envelope->'provider_approval_state') from public.operations_finance_invoice_streams h join public.operations_finance_invoice_snapshots s on s.organization_id=h.organization_id and s.source_organization_id=h.source_organization_id and s.invoice_id=h.invoice_id and s.source_revision=h.current_revision where h.invoice_id='23232323-2323-4232-8232-232323232323'),
 'v2_sources',(select coalesce(jsonb_agg(jsonb_build_object('invoice_id',h.invoice_id,'id',s.id,'current_revision',h.current_revision,'body_sha256',s.body_sha256,'currency',s.envelope->'currency','net_minor',s.envelope->'recipient_net_minor','allocation_minor',s.envelope#>'{allocations,0,amount_minor}','allocation_count',jsonb_array_length(s.envelope->'allocations'),'accounting_state',s.envelope->'accounting_state','settlement_state',s.envelope->'settlement_state','provider_approval_state',s.envelope->'provider_approval_state') order by h.invoice_id),'[]'::jsonb) from public.operations_finance_credit_v2_streams h join public.operations_finance_credit_v2_snapshots s on s.organization_id=h.organization_id and s.source_organization_id=h.source_organization_id and s.invoice_id=h.invoice_id and s.source_revision=h.current_revision),
 'assignment_heads',(select coalesce(jsonb_agg(to_jsonb(h) order by h.source_anchor),'[]'::jsonb) from public.operations_obligation_credit_assignment_heads h),
 'assignment_events',(select coalesce(jsonb_agg(jsonb_build_object('event_id',e.event_id,'revision',e.revision,'source_anchor',e.source_anchor,'baseline_event_id',e.baseline_event_id,'original_binding_event_id',e.original_binding_event_id,'credit_snapshot_id',e.credit_snapshot_id,'amount_minor',e.proof->'amount_minor','credit_invoice_id',e.proof->'credit_invoice_id','proof_fingerprint',e.proof_fingerprint,'proof_valid',e.proof_fingerprint=encode(sha256(convert_to(e.proof::text,'UTF8')),'hex'),'actor_system_user_id',e.actor_system_user_id,'command',e.command) order by e.source_anchor,e.revision),'[]'::jsonb) from public.operations_obligation_credit_assignments e),
 'capacity_heads',(select coalesce(jsonb_agg(to_jsonb(h) order by h.source_anchor),'[]'::jsonb) from public.operations_obligation_credit_capacity_heads h),
 'capacity_events',(select coalesce(jsonb_agg(jsonb_build_object('event_id',e.event_id,'revision',e.revision,'source_anchor',e.source_anchor,'original_anchor',e.original_anchor,'assignment_event_id',e.assignment_event_id,'currency',e.currency,'reserved_minor',e.reserved_minor,'original_amount_minor',e.original_amount_minor,'retained_aggregate_minor',e.retained_aggregate_minor,'proof_valid',e.source_proof_fingerprint=encode(sha256(convert_to(e.source_proof::text,'UTF8')),'hex'),'actor_system_user_id',e.actor_system_user_id,'command',e.command) order by e.source_anchor,e.revision),'[]'::jsonb) from public.operations_obligation_credit_capacity_events e)
);
rollback;
